### ISSUE TITLE
RFC: Python Library for ThreatExchange

### ISSUE THREAD

**Issue by mgoffin** [facebook/ThreatExchange#1]
I wanted to build a Python Library that would allow developers to quickly integrate with ThreatExchange. I've started the work here:

    https://github.com/mgoffin/ThreatExchange/tree/pytx
    (comparison: https://github.com/facebook/ThreatExchange/compare/master...mgoffin:pytx)

The goals I have for this are:

* Easy to install (pip install pytx).
* Easy to work with for quick prototyping and production-quality development.
  * Not just a wrapper around the API. Provide easy-to-use methods for tasks.
  * Rich vocabulary list to make code more resilient against name-changes.
  * Thorough documentation (both in code and elsewhere) so getting up-to-speed is quick and painless.
* Useful results that are easy to loop over, parse, and ingest.
* Classful interfaces to the different object types and results.
* Flexible for future API enhancements.
* Test cases to keep code in working order and automate builds for validation.
* Example scripts to get people started.

The code is still very much a WIP but I wanted to get it out there for visibility, comments, and direction. I think it is a decent foundation to work from, but a lot can be done to make this better. Some of the goals haven't been started because I think the foundation needs to mature a bit before they can be worked on (like Classful objects and results, example scripts, test cases, more documentation, etc.).

Ultimately I'd like to get this in a state where it's stable enough to submit a PR, get some development interest from other community members, then get it up on PyPi for quick installation.

Here's an example of using this library in its current form:

```python
import pytx
import pytx.vocabulary as v

p = pytx.pytx('<app-id>', '<app-secret>')

# Find malware using approximate matching for "www.facebook.com"
i = p.malware_analyses(text="www.facebook.com")

# Find Indicators using strict matching for "www.facebook.com"
i = p.threat_indicators(text="www.facebook.com", strict_text=True)

# Get a list of ThreatExchange members.
i = p.threat_exchange_members()

# Get a list of malware objects associated with a specific object.
i = p.objects('<object-id>', connection=v.Connection.MALWARE_ANALYSES)

# Quickly inspect and loop over results
print i
for x in i:
    print x
```

Thanks!

**Comment by jessek** [comment]
This is fantastic! Thank you for taking the time to write this library. I think it will be a valuable resource to the community and we're glad you're getting involved.

Please let me know if you have any questions. We're going to changing some things around in the coming weeks and will need to make some minor changes to your code.

I'm looking forward to the PR!

**Comment by mgoffin** [comment]
Thanks! I'm going to continue working on a few things and see if I can get some more eyes on the general concept. If you or anyone there have any opinions on this I'd love to hear about them as well!

Hopefully we can nail down a decent layout for the code so we can be confident it won't change drastically. If all goes well the changes you are all looking to make in the short term should be fairly simple to include :)

**Comment by mgoffin** [comment]
For anyone who swings by to look I made another branch which uses similar code but is classful:

https://github.com/mgoffin/ThreatExchange/tree/pytx_classful

The goal here is that you instantiate an object once, provide your APP-ID and APP-SECRET, then from there on out you can use that object to do basically everything. Example:

```python
from pytx import ThreatIndicator
from pytx.vocabulary import Status as s
from pytx.vocabulary import ThreatIndicator as t

t = ThreatIndicator(app_id='<app-id>', app_secret='<app-secret>')
i = t.objects(text="www.facebook.com")
for x in i:
    x.set(t.STATUS, s.MALICIOUS)
    x.save()
```

In this example each object returned is an instantiated instance of `ThreatIndicator` with your credentials already set, so you can immediately turn around and do things like modify the `status` to be `MALICIOUS` and submit the change back.

I'm thinking I like this better so I might push the development in this direction unless people oppose.

**Comment by hammem** [comment]
That sounds great.  It'll save us a bunch of time in the end.  Can't wait
for the merge request back to master :)

One thing we've been toying with is to build a 'translation toolkit' in
python to support getting data in CSV, STIX/TAXII, OpenIOC or other formats
in/out of ThreatExchange.  From what you've built so far, you're making it
easy!

**Comment by mgoffin** [comment]
We could add a "translations" folder to pytx which can contain tools necessary for converting data to/from ThreatExchange. I'll be honest my main focus would not be in this area, but it would at least provide a place for people who want to contribute these types of features. It would surely benefit companies looking to push data into ThreatExchange but have data in weird formats :)

**Comment by mgoffin** [comment]
Given that the PR is up and we're conversing there, this issue can be closed :)

**Comment by jessek** [comment]
TIL that Github does not automatically close the issue when the pull request is landed. Thanks!

**Comment by mgoffin** [comment]
It was my bad not including the issue # in one of the commits!
