### ISSUE TITLE
Allow custom headers for pytx

### ISSUE THREAD

**Issue by mgoffin** [facebook/ThreatExchange#103]
Similar to how we allow people to set a proxy, or setup logging, we should allow them to setup custom headers and then use those headers for all requests going forward.

Example code:

```python
headers = {
    'User-Agent': 'Foo'
}

response = requests.get(url, headers=headers)
```

**Comment by mgoffin** [comment]
#104

**Comment by jessek** [comment]
Can this be closed now?

**Comment by mgoffin** [comment]
Yes sir! Thank you!

**Comment by motiwarifacebook** [comment]
Closed by PR, we're good.
