### ISSUE TITLE
Add method to search for exact text

### ISSUE THREAD

**Issue by jessek** [facebook/ThreatExchange#105]
There should be a way to search for an exact match. For example, when searching for evilevillabs.com, the query should match for _exactly_ evilevillabs.com, not test.evilevillabs.com or i-know-somebody-at-evilevillabs.com.

**Comment by RyPeck** [comment]
@Jessek - What about a method that allows you to search for an exact indicator?

**Comment by jessek** [comment]
Are we saying the same thing @RyPeck ? What is different between those two things?

**Comment by RyPeck** [comment]
Possibly - Would your function also match on description fields that contain exactly a query?

**Comment by jessek** [comment]
Currently, when you use the 'strict_text' parameter, the text is limited to the primary field being searched. (See https://github.com/facebook/ThreatExchange/issues/84). I'd presume to do the same thing for exact matching, too.

**Comment by Junquer-G** [comment]
In fact , i'm using the "strict_text" parameter, but i'm still getting some results i don't want.

For example, when i query "strict-text=true&text=as.com, i get results from "swm-as.com", which i don't want,

threat_indicators?text=as.com&strict_text=true

Am i doing something wrong?or this is the expected behaviour?

**Comment by jessek** [comment]
This is the expected behavior. Our searching system sees characters like dashes and dots as separators. Using exact matches prevents your search string from being matched inside of a word (e.g. "baas.com"), but not with a separator (swim-as.com).

**Comment by jessek** [comment]
We have revised the strict_text parameter! It now works as you've requested. :)
