### ISSUE TITLE
PYTX: Some objects don't support all query parameters

### ISSUE THREAD

**Issue by motiwarifacebook** [facebook/ThreatExchange#107]
ThreatDescriptor.objects should support queries by REVIEW_STATUS and SHARE_LEVEL
Malware.objects should support queries by SAMPLE_TYPE

**Comment by motiwarifacebook** [comment]
Furthermore, I'm having errors trying to get the fields added_on, Confidence, expired_on, last_updated, precision, review_status, severity, and threat_type. For example script to repro this, see: http://pastebin.com/FsbUSddM

**Comment by mgoffin** [comment]
We resolved the above issues because those are fields which are not normally returned by TXI API queries unless they are specifically requested.

#110 should solve your other problem :)

**Comment by motiwarifacebook** [comment]
Also just realized that Malware.objects should support queries by sample_type. I'll add that to this issue.

**Comment by mgoffin** [comment]
I believe we can close this now?

**Comment by motiwarifacebook** [comment]
Yes thanks!

**Comment by motiwarifacebook** [comment]
Yes thanks!

**Comment by motiwarifacebook** [comment]
Yes thanks!

**Comment by motiwarifacebook** [comment]
Yes thanks!
