### ISSUE TITLE
[py-tx] Fetching for fb_threatexchange api for some privacy groups is stopping early

### ISSUE THREAD

**Issue by BarrettOlson** [facebook/ThreatExchange#1191]
`threat_exchange fetch` is not yields all results in one of the dataset sets stopping thinking it is up to date when it is still missing data.

repro (where <ID> is the pg id)
```
threatexchange config collab edit fb_threatexchange --create --privacy-group <ID> signal_set 
threatexchange fetch
```

After fetching for awhile the command will return and build the index early.

**Comment by Dcallies** [comment]
@BarrettOlson - I believe we traced the issue to the Facebook graph API and have fix this now, is that correct?

**Comment by BarrettOlson** [comment]
yes, I believe that is correct. Closing for now but can reopen if we see it again
