### ISSUE TITLE
[py-tx] update fetch defaults for fb_threat_exchange to download all data even for not yet supported signal types

### ISSUE THREAD

**Issue by BarrettOlson** [facebook/ThreatExchange#1192]
We might want this to be more configurable but if we have the default fetch all signals then we will prevent needing to refetching the dataset when type interfaces change/are added

**Comment by Dcallies** [comment]
Agree should be configurable in the long term, first pass let's just get it correct.

I have an open question of how to handle configuration changes that invalidate the state, I have ideas but no solution just yet.

**Comment by Dcallies** [comment]
I think this is done now: #1198

It was supposed to be its own PR, but the commit accidentally got pulled and landed before I realized: https://github.com/facebook/ThreatExchange/pull/1198/commits/3299ed9be1f0525319b453575e611e70e5755f19
