### ISSUE TITLE
[Documentation] README for StopNCII credentials out of order

### ISSUE THREAD

**Issue by thedanielsun** [facebook/ThreatExchange#1245]
SUBSCRIPTION_KEY, FUNCTION_KEY are reversed in the README

README section: https://github.com/facebook/ThreatExchange/blob/31a044d80766998101ec7ac8a3afe87ea75aff64/python-threatexchange/README.md?plain=1#L198

API impl: https://github.com/facebook/ThreatExchange/blob/main/python-threatexchange/threatexchange/exchanges/impl/stop_ncii_api.py#L79

**Comment by BarrettOlson** [comment]
Thanks! 
Looked through the code and it appears consistent. The variable order was just swapped for the README. The only place in the code I see the order from the README is when keyword args are used, therefore I think we are safe just updating the README but I will leave to @Dcallies to confirm.

**Comment by BarrettOlson** [comment]
Addressed in #1246
