### ISSUE TITLE
[py-tx] Typing of SignalExchangeAPIWithSimpleUpdates is too Generic | remove use of t.Any

### ISSUE THREAD

**Issue by BarrettOlson** [facebook/ThreatExchange#1255]
See #1254  

In order pass `mypy` the last arg in the type of 
`SignalExchangeAPIWithSimpleUpdates` was made generic. 

Previous value: `state.TFetchedSignalMetadata` which gave error 
`threatexchange/exchanges/signal_exchange_api.py:269: error: Variance of TypeVar "state.TFetchedSignalMetadata" incompatible with variance in parent type [type-var]`

Having this be generic is risky because `SignalExchangeAPIWithSimpleUpdates` is one of the single most important interface in pytx

------
Notes from brief attempt to fix: When Barrett attempted to replace value with `state.TUpdateRecordValue` mypy broke further along in files using `SignalExchangeAPIWithSimpleUpdates` so there may more bugs hidden behind this issue already.

**Comment by Dcallies** [comment]
Fixed by #1670 I believe
