### ISSUE TITLE
[hma] Clicking Sync button on the webui doesn't do anything

### ISSUE THREAD

**Issue by kyuilgo** [facebook/ThreatExchange#1280]
![Screen Shot 2023-03-23 at 4 28 32 PM](https://user-images.githubusercontent.com/128712283/227386604-320a9c28-4120-4751-bff6-921aacc334f7.png)

I don't see any "fetch" logs in the fetcher log group after I click the sync button in settings. I think it may not be hitting api_root since I don't see anything in that log group either. The -1 in the PDQ Hashes available is a little suspect as well. Could you take a look?

**Comment by Dcallies** [comment]
HMA 1.0 is dead as of #1556 !
