### ISSUE TITLE
[HMA] graph API 9.0 hardcoded, now deprecated 

### ISSUE THREAD

**Issue by Dcallies** [facebook/ThreatExchange#1295]
https://developers.facebook.com/docs/graph-api/changelog/version9.0/

HMA appears to be hard coding version 9.0, which stopped working in February. I believe we can avoid specifying a version number, which will force it to work on the most recent version, alternatively we can just bump it.

**Comment by BarrettOlson** [comment]
hmm, I can still query the API just fine for v9.0 via curl and v9.0 is hardcoded in python-threatexchange (not hma) https://github.com/facebook/ThreatExchange/blob/main/python-threatexchange/threatexchange/exchanges/clients/fb_threatexchange/api.py#L84

Issue is still valid though as we should avoid hardcoding a not longer officially supported api version.
