### ISSUE TITLE
[py-tx][HMA-in-a-bottle] Modularising py-tx -- Draft roadmap

### ISSUE THREAD

**Issue by Sam-Freeman** [facebook/ThreatExchange#1298]
Offline, we synced on what we want to accomplish in an attempt to modularise the py-tx library to improve the onboarding of potential partners. The things that we want to cover in this effort at a high level are:
* Port components of the CLI into the base library 
* Design/Create an API for py-tx (essentially putting what is possible with the CLI into an API)
* Modularise the hasher and matcher components and make them deployable with Docker
* Modularise and improve the plug-ability of the FAISS index (cc @NikolayOG)

@dougneal to comment with additional areas we are looking to improve.

**Comment by dougneal** [comment]
A starting point for the library part could be to create `hashing` and `matching` modules (directories) and move the "business end" of the CLI commands over into them.

**Comment by NikolayOG** [comment]
module for `ingestion`  would also be needed

**Comment by Sam-Freeman** [comment]
Created branch `hma-in-a-bottle` for us to use for _rapid_ development here

**Comment by dougneal** [comment]
And we're looking for a new name...

**Comment by Dcallies** [comment]
Closing this guy for stale, though many of these ideas are still worth exploring!
