### ISSUE TITLE
Edits to the example code (in bold)

### ISSUE THREAD

**Issue by bsoman3** [facebook/ThreatExchange#130]
from pytx.access_token import access_token
from pytx import ThreatDescriptor
from pytx.vocabulary import ThreatDescriptor as td
**from pytx.vocabulary import ThreatIndicator as ti**
access_token('<app-id>', '<app-secret>')

results = ThreatDescriptor.objects(text='www.facebook.com')
for result in results:
  **print result.get(td.THREAT_TYPE)**

results = ThreatDescriptor.objects(type_='IP_ADDRESS',
                                       text='127.0.0.1')
for result in results:
  print result.get(ti.INDICATOR)

**Comment by wxsBSD** [comment]
What file are you suggesting be edited? I went grepping for this and my guess is you want to make changes to pytx/README.rst, but it's not entirely clear.

**Comment by mgoffin** [comment]
We fixed this with the last two commits to master :) Thank you for bringing this up!

**Comment by wxsBSD** [comment]
My grep-fu was weak on this one. Thanks, as always, @mgoffin. I owe you a BBQ dinner or something. ;)

**Comment by bsoman3** [comment]
thanks @wxs, and @mgoffin. Will be more clear with my issues in the future.
