### ISSUE TITLE
[hma] submitting content gets stuck between "hashed" and "matched"

### ISSUE THREAD

**Issue by kyuilgo** [facebook/ThreatExchange#1300]
I created a test bank and uploaded a photo member to that bank. Using that same photo, I submitted using the submit content UI on the webUI. The pipeline has been stuck between hashed and matched for quite some time now.

<img width="587" alt="Screen Shot 2023-03-29 at 2 31 50 PM" src="https://user-images.githubusercontent.com/128712283/228672752-cf80ba2a-9b90-4d13-b3a8-87abcb58fe5c.png">

**Comment by Dcallies** [comment]
Thanks again for the report @kyuilgo! @BarrettOlson and I are talking about putting dedicated time to try and burn down some of the issues you are reporting.

Do you have any log messages around this time that might be a smoking gun? Errors?

This is between two SQS queues.

**Comment by Dcallies** [comment]
HMA 1.0 is dead as of #1556 !
