### ISSUE TITLE
NONCE | definition in the Cambridge English Dictionary

### ISSUE THREAD

**Issue by Karkarp** [facebook/ThreatExchange#1306]
https://dictionary.cambridge.org/us/dictionary/english/nonce

**Comment by Dcallies** [comment]
Hey @Karkarp, please provide more context in your issues. You've opened 3 with only a link. 

Please provide:
1. A summary that gives an indication of what the issue is
2. A long description of the issue, or if it's for a bug, steps for reproducing it
