### ISSUE TITLE
[pytx] Added privacy_type to Malware objects

### ISSUE THREAD

**Issue by motiwarifacebook** [facebook/ThreatExchange#137]
Privacy_type is missing on pytx.Malware objects and in pytx.vocabulary.Malware, despite being a field in TX for Malware Analyses

**Comment by mgoffin** [comment]
I believe this was due to Malware being in a read-only state. We will need to add privacy_type and privacy_members at the very least. Not sure if anything else is missing. Also not sure if these changes also apply to MalwareFamily objects and if either are missing.

**Comment by bryongloden** [comment]
👍
