### ISSUE TITLE
Name change for ruby lib.

### ISSUE THREAD

**Issue by tiegz** [facebook/ThreatExchange#142]
I'd like to propose changing the Ruby lib name from `ThreatExchange` to `threat_exchange` everywhere.

Snakecase is the most common [convention](https://en.wikipedia.org/wiki/Snake_case) in Ruby (e.g. list of gems on [Rubygems](https://rubygems.org/gems)).

It's mostly a cosmetic change, but could help adoption of the library.

**Comment by wxsBSD** [comment]
This seems fine, but it may break existing scripts which use it. Do you have any sense for how many people this may break? I'm certainly not opposed to it but want to attempt to minimize breakage.

**Comment by tiegz** [comment]
@wxsBSD the Ruby lib was a little stale until last week, so I bet it won't be too bad. We may even be able to keep an alias around for a bit. I'll try it out later and might PR this.

**Comment by wxsBSD** [comment]
Awesome. I'll be closing this out and await a PR. :)
