### ISSUE TITLE
USD$.1234567890.00

### ISSUE THREAD

**Issue by whatsappsuppoit** [facebook/ThreatExchange#1473]
[]()![01763016333.pdf](https://github.com/facebook/ThreatExchange/files/13572219/01763016333.pdf)

ইউনিক্স-সদৃশ
নিবন্ধের বিবরণ যোগ করুন
ইউনিক্স-সদৃশ (ইংরেজি: Unix-like; মাঝেমধ্যে যাকে *নিক্সও বলা হয়) অপারেটিং সিস্টেম হলো যেগুলোর কার্যপ্রণালী ও ব্যবহারে ইউনিক্সের সাথে মিল রয়েছে, যেগুলো প্রয়োজনীয়ভাবে কোন একক ইউনিক্স বিবরণীর কোন সংস্করণে অনুমোদিন নয়। আর ইউনিক্স-সদৃশ অ্যাপলিকেশন হলো এমন অ্যাপলিকেশন যেটি সংশ্লিষ্ট ইউনিক্স কমান্ড বা ইউনিক্স শেলের মত কাজ করে। এ শব্দটিকে সংজ্ঞায়িত করার কোন প্রযুক্তিক প্রামাণিক সংজ্ঞা নেই, এবং কোন অ্যাপলিকেশন বা অপারেটিং সিস্টেমকে "ইউনিক্স-সদৃশ" বলা যাবে কি না তা নিয়ে ভিন্ন মত ও বিতর্ক রয়েছে।

১৯৬৯ থেকে শুরু করে ইউনিক্স ও ইউনিক্স-সদৃশ সিস্টেমসমূহের বিবর্তন
বেল ল্যাবসের ইউনিক্স বা এর বৈশিষ্ট্যসমূহকে ফুটিয়ে তুলতে উন্নয়ন করা অধিকাংশ মুক্ত ও উন্মুক্ত উৎসের সফটওয়্যারই ইউনিক্স-সদৃশ। লাইসেন্সকৃত ইউনিক্স উৎস কোড ও বাণিজ্যিক ও মালিকানাধীন একইরকম সফটওয়্যারও ইউনিক্স-সদৃশ বলে গণ্য করা হতে পারে।

সংজ্ঞা
ওপেন গ্রুপ ইউনিক্স ট্রেডমার্কের মালিকানায় রয়েছে, এবং একক ইউনিক্স বিবরণীর নিয়ন্ত্রণেও তারা রয়েছে, যেখানে সনদের চিহ্ন হিশেবে "ইউনিক্স" নামটি ব্যবহার করা হয়। তারা "ইউনিক্স-সদৃশ" বিষয়টিকে সমর্থন করে না এবং এটাকে তাদের ট্রেডমার্কের অপব্যবহার হিশেবে গণ্য করে। তাদের নীতিমালায় "ইউনিক্স শব্দটিকে ইংরেজিতে বড় অক্ষরে লিখতে উৎসাহিত করা হয় (ইংরেজি: UNIX), এবং "সিস্টেম"-এর মত সাধারণ শব্দের বদলে ব্যান্ডিং বিশেষণ হিশেবে ইউনিক্স ব্যবহার করতে বলা হয়। 

অন্যান্য পক্ষসমূহ "ইউনিক্স"কে একটি আরও সাধারণ ট্রেডমার্ক হিশেবে গণ্য করে। অনেকে তাদের অপারেটিং সিস্টেমের সাথে *নিক্স বা UN*X যুক্ত করে ইউনিক্স-সদৃশ বৈশিষ্ট্যের প্রতি ইঙ্গিত করে, যেমন, লিনাক্স, মিনিক্স, এইচপি-ইউএক্স, আইআরআইএক্স, আলট্রিক্স এবং এক্সএনইউ। এ নামকরণের পদ্ধতিটি কোন সুনির্দিষ্ট নিয়ম নেই, তবুও দেখলে বুঝা যায় যে তারা ইউনিক্স-সদৃশ। তবে কিছু ইউনিক্স-সদৃশ অপারেটিং সিস্টেমে আবার এমন নামকরণ নীতি একেবারেই অনুসরণ করা হয় না, যেমন- ডারউইন, ম্যাকওএস, সোলারিস অথবা ফ্রিবিএসডি।

২০০৭ সালে ওয়েন আর গ্রে ইউনিক্সকে ট্রেডমার্ক হিশেবে রাখতে মামলা করেন এবং মামলাটি হেরে যান।

ইতিহাস

ইউনিক্স-সদৃশ অপারেটিং সিস্টেমসমূহের ইতিহাস।
১৯৭০ ও ৮০র দশকের শেষের দিকে "ইউনিক্স-সদৃশ" সিস্টেমসমূহ আসতে শুরু করে। অনেকগুলো মালিকানাধীন সংস্করণ, যেমন ইদ্রিস (১৯৭৮), ইউএনওএস (১৯৮২), এবং ইউনিফ্লেক্স (১৯৮৫), বাণিজ্যিক প্রতিষ্ঠানসমূহকে ইউনিক্সের একাডেমিক ব্যবহারকারীদের মত সুবিধা দিতে উন্নয়ন করা হয়।

যখন ১৯৭৯ সালে এটি এন্ড টি কম মূল্যের ইউনিক্সের বাণিজ্যিক বাইনারি সাব-লাইসেন্সিঙের অনুমোদন দেয়, এটার উপর ভিত্তি করে অনেকগুলো মালিকানাধীন সিস্টেম উন্নয়ন করা হয়, যার মধ্যে রয়েছে এআইএক্স, এইচপি-ইউএক্স, সানওএস, আলট্রিক্স এবং জেনিক্স। এ সিস্টমেগুলো মালিকানাধীন নকলসমূহকে তাদের স্থানচ্যুত করে। সিস্টেমগুলোর মধ্যে সামঞ্জস্য বিধানের প্রয়োজনীয়তা থেকেই পোজিক্স ও একক ইউনিক্স বিবরণীর উৎপত্তি ঘটে।

অনেকগুলো মুক্ত, বিনামূল্যের বা কমমূল্যের বা বাধাহীন ইউনিক্স সিস্টেম ৮০ ও ৯০র দশকে আসা শুরু করে, যার মধ্যে আছে ৪.৪বিএসডি, লিনাক্স, এবং মিনিক্স রয়েছে। এগুলোর অনেগুলোই বাণিজ্যিক "ইউনিক্স-সদৃশ" সিস্টেম, যেমন বিএসডি/ওএস, ও ম্যাকওএসের ভিত হিশেবে ব্যবহৃত হয়ে এসেছে। ইন্টেল-ভিত্তিক ম্যাক কম্পিউটারসমূহে চলা অনেকগুলো (ম্যাক) ওএস এক্স/ম্যাকওএস একক ইউনিক্স বিবরণী কর্তৃক অনুমোদন পেয়েছে।  বিএসডি সংস্করণসমূহ বার্কলেতে বেল ল্যাবসের ইউনিক্স উৎস কোড থেকে ক্যালিফোর্নিয়া বিশ্ববিদ্যালয়ের উন্নয়ন করা ইউনিক্সের উত্তরসূরি। তবে এখন এটি এন্ড টি-এর কোন কোডই বিএসডি কোড ভিতে নেই।

শ্রেণীসমূহ
ডেনিস রিচি, ইউনিক্সের মূল নির্মাতাদের একজন, জানান ইউনিক্স-সদৃশ সিস্টেম যেমন লিনাক্স হলো ডি ফ্যাক্টো ইউনিক্স সিস্টেম।  এলরিক এস রেয়মন্ড ও রব ল্যান্ডলির মতে তিন প্রকারের ইউনিক্স-সদৃশ সিস্টেম রয়েছে

জেনেরিক ইউনিক্স
ঐতিহাসিক এটি এন্ড টি কোঢবিতের সাথে সংযোগ থাকা সিস্টেমসমূহ। সবগুলো না হলেও, অধিকাংশ বাণিজ্যিক ইউনিক্স সিস্টেমই এ শ্রেণীতে পড়ে। বিএসডি সিস্টেমসমূহ, যেগুলো ক্যালিফোর্নিয়া বিশ্ববিদ্যালয়, বার্কলের গবেষণার উত্তরসূরি, সেগুলোও এ শ্রেণীতে পড়ে। এ সিস্টেমগুলোতে প্রয়োজনীয়ভাবে এটি এন্ড টির কোড থাকা লাগবে না।

ট্রেডমার্ক অথবা ব্র্যান্ডকৃত ইউনিক্স
এ সিস্টেমগুলো বেশীরভাগই বাণিজ্যিক, যেগুলো ওপেন গ্রুপ দ্বারা একক ইউনিক্স বিবরণীতে সনদপ্রাপ্ত এবং ইউনিক্স নাম ব্যবহারের অনুমোদনপ্রাপ্ত। এদের বেশীরভাগই সিস্টেম ভি-এর কোডভিতের উত্তরসূরি। ম্যাকওএস ১০.৫ বা তার পরের সংস্করণগুলো বিএসডি উত্তরসূরি হলেও, এগুলো একক ইউনিক্স বিবরণীতে সনদপ্রাপ্ত। অনেকগুলো পুরোনো ইউনিক্স সিস্টেম এ সংজ্ঞায় আর পড়ে না।

ফাংশনাল ইউনিক্স
ইউনিক্স বিবরণীর সাথে মিলে যায় এমন আচরণ করা, যেখানে একটি শেল এর লগইন ও অন্যান্য কমান্ড লাইন সেশন নিয়ন্ত্রণ করে, এমন যেকোন ইউনিক্স-সদৃশ সিস্টেমই এ শ্রেণীতে পড়ে। আরও নির্দিষ্ট করে বলতে গেলে লিনাক্স ও মিনিক্সের মত সিস্টেমগুলোই এ শ্রেণীভুক্ত।

২০০১ এর দিকে লিনাক্সকে পোজিক্স চেয়ার অ্যান্ড্রু জোসি কর্তৃক শুধুমাত্র ১ ডলারের বিনিময়ে বিনামূল্যের সাহায্য সহ সনদপ্রাপ্ত হওয়ার সুযোগ দেয়া হয়। এরপরে কিছু কাজও করা হয়, যেখানে লিনাক্স প্রামাণিক ভিত ও পোজিক্স প্রামাণিকের মধ্যে অমিলের তালিকাও হয়।  তবে ২০০৫ সালের আগস্টে এলএসবি কার্য গোষ্ঠীর আগ্রহের অভাবে এ প্রকল্পটির সমাপ্তি হয়।

সামঞ্জস্যতা লেয়ারসমূহ
কিছু ইউনিক্স-সদৃশ নয় এমন অপারেটিং সিস্টেমসমূহতেও ইউনিক্স-সদৃশ সামঞ্জস্যতা লেয়ার প্রদান করা হয়, যেটি একে কিছু ইউনিক্স-সদৃশ কর্মক্ষমতা প্রদান করে।

আইবিএম জি/ওএসের ইউনিক্স সিস্টেম সেবাসমূহ ট্রেডমার্ক ইউনিক্সের সাথে প্রতিযোগিতার জন্য যথেষ্ট।
সিগউইন ও এমএসওয়াইএস দুটোই মাইক্রোসফট উইন্ডোজ ব্যবহারকারী এপিআই-এর উপর গ্নু পরিবেশ সংযুক্ত করার মাধ্যমে জনপ্রিয়

**Comment by Dcallies** [comment]
This appears to be spam, please don't click on the link.
