### ISSUE TITLE
pytx ThreatTag.objects() call uses ThreatDiscriptor parameters 

### ISSUE THREAD

**Issue by seanthegeek** [facebook/ThreatExchange#153]
@mgoffin

In pytx 0.5.3, I noticed that `ThreatTag.objects()` actually uses the same parameters as `ThreatDiscriptor.objects()`. e.g `strict_text=false&include_expired=false`, rather than the correct ones for `ThreatTag`. This causes an HTTP 500 error.

**Comment by mgoffin** [comment]
Thanks for letting me know! I suspect defaulting those will no longer work with ThreatTag being added to the mix. Since those are the defaults I'll rework the logic to only include them if they are set to a non-default value (`true`).

**Comment by mgoffin** [comment]
@seanthegeek I am doing the following:

```python
>>> from pytx import ThreatTag
>>> ts = ThreatTag.objects(text='malware', request_dict=True)
>>> ts
{'url': 'https://graph.facebook.com/v2.8/threat_tags/?text=malware&strict_text=false&include_expired=false', 'body': None, 'type': 'GET'}
>>> ts = ThreatTag.objects(text='malware')
>>> count = 0
>>> for t in ts:
...     count += 1
...
>>> count
5
>>>
```

It seems to be working for me, however I might be reproducing wrong. Could you provide an example request using pytx code that causes the HTTP 500 error? Thanks!

**Comment by seanthegeek** [comment]
Maybe it's because I'm trying to get a list  of all tags?

`
from pytx import ThreatTag

count = 0
results = ThreatTag.objects()
for result in results:
    count += 1
print(count)`

**Comment by mgoffin** [comment]
Correct. You need to provide some sort of text to search on. If you put this in your browser:

`https://graph.facebook.com/v2.8/threat_tags/?access_token=foo|bar`

replacing with your access token, you'll see the same error coming back.

**Comment by seanthegeek** [comment]
Ah, in that case, I wonder why `pytxFetchError` is not raised like in is when missing attributes for `ThreatDiscriptor`?

**Comment by mgoffin** [comment]
I suspect because with `ThreatDescriptor` you aren't required to have a value in the `text` parameter if you include date ranges. I'd have to go back and check to see why it's not tripping.
