### ISSUE TITLE
pytx- why does a day return more ThreatDiscriptors than a month?

### ISSUE THREAD

**Issue by seanthegeek** [facebook/ThreatExchange#154]
Hi everyone,

I'm just starting to explore ThreatExchange with pytx, and I'm getting odd results.

```
ThreatDescriptor.objects(since="yesterday",
until="now")
```

Returns 500+ results

```
ThreatDescriptor.objects(since="-1 month",
until="now")
```

Returns 4 results

What am I missing? Shouldn't that return up to 1000 results?

**Comment by mgoffin** [comment]
There is an ongoing issue with inaccurate results that isn't pytx related. For some reason you can perform the same query one after the other and you'll get less, more, or the same results as the previous run of the same query. There's several conversations about it in the Facebook group. You can make the problem slightly less troublesome by bumping the limit up to something like 1000, but it doesn't resolve the underlying problem.

You can also turn on logging and tail the log while you run these queries and loop over them. You can see the cursor changing and it following the `next` URI until there isn't one to follow. As far as pytx knows, that's the end of the results.

**Comment by seanthegeek** [comment]
Thanks for the info. I just got access to the Facebook group. I hope they get this fixed soon. I Thought I was going crazy! Any idea how long this have been going on?
