### ISSUE TITLE
pytx should set sane defaults for fields returned and use them by default

### ISSUE THREAD

**Issue by mgoffin** [facebook/ThreatExchange#158]
Each main class has an `_default_fields` attribute which is a list of fields that are supposed to be "default fields returned by ThreatExchange when you perform a query."

We should change this so that `_default_fields` is a list of "useful" fields determined by those that use the data. Once those lists are fixed up, we should change `.objects()` to use what is in `cls._default_fields` if the `fields` argument is still `None`. This will allow people to override and specify the fields they want to use, otherwise they will get what pytx considers the default ones.

**Comment by wxsBSD** [comment]
As the person who ran into this and contacted @mgoffin about it, I'm in agreement. It was very counter-intuitive to see this behavior by default, and I think the suggested change is a good one.

To provide a bit of context around this, I was helping someone use pytx to search for all PE files, but it wasn't clear to me what the appropriate search term to use is. Do I use `Malware.objects(sample_type='PE')` or something else? To answer this question we searched using `Malware.objects(md5='foo')` (where `foo` was an MD5 of a PE file we knew was in TE). We expected to see the `sample_type` field populated with the appropriate value, but instead we got None. It wasn't until we specified `fields=['sample_type']` in the call that we got the appropriate value returned to us.

As I said, this is a very counter-intuitive behavior and I would suggest changing it so `_default_fields` is some sane list of things that are returned for each object unless explicitly overridden by the caller.

**Comment by hammem** [comment]
This makes perfect sense to me.  I often find myself doing things like `fields=ThreatDescriptor._default_fields` in my queries.

I'd say we make this change, as I don't think(?) this would cause fields that are currently returned by default to disappear on folks.
