### ISSUE TITLE
[hma] Bad redirects on dev page

### ISSUE THREAD

**Issue by sbruens** [facebook/ThreatExchange#1591]
The dev handlers (e.g. `/dev/factory_reset`) redirect to `/dev/` which doesn't exist. It makes it seem like the action failed, when it's just the redirect that is bad. Example here: https://github.com/facebook/ThreatExchange/blob/d4d343c435bb048610de91087e608c6ebcb24923/hasher-matcher-actioner/src/OpenMediaMatch/blueprints/development.py#L104

I think it can be done with `redirect(url_for(ui.bp.home))`? Let me give it a try and send a PR.

**Comment by Dcallies** [comment]
Might be a breakage from when I moved this out of /ui/ where this redirect made sense. I think your fix looks right.
