### ISSUE TITLE
[py-tx][ez] Update contact addresses from @fb -> @meta

### ISSUE THREAD

**Issue by Dcallies** [facebook/ThreatExchange#1615]
https://github.com/facebook/ThreatExchange/blob/main/python-threatexchange/setup.py#L46

Still has the @fb.com address, which we should update to @meta.com

**Comment by manojks1999** [comment]
Hi @Dcallies ,
Can I work on this?

**Comment by Dcallies** [comment]
Go for it @manojks1999 !

**Comment by Dcallies** [comment]
I found another reference in the code, so someone should just grep all the locations and update them :P
