### ISSUE TITLE
[py-tx] Use typing.Self in more places

### ISSUE THREAD

**Issue by Dcallies** [facebook/ThreatExchange#1616]
Ref: https://realpython.com/python-type-self/

Since py-tx is a bit aged at this point, we've straddled a few quality of life improvements with typing.

We can replace a lot of forward-declared self references to Self instead.

Here's a command you could use to look for opportunities:

```
python-threatexchange# grep -r -n " -> [\"']" --include='*.py' .
```

Here's one file that comes up in that list: https://github.com/facebook/ThreatExchange/blob/main/python-threatexchange/threatexchange/signal_type/signal_base.py#L22

**Comment by manojks1999** [comment]
Hi @Dcallies , can I work on this?

**Comment by Dcallies** [comment]
It's all yours! Let me know if you don't think you won't be able to get to it in the next week!

**Comment by suvamsh** [comment]
We can't do this until we update to python 3.11
