### ISSUE TITLE
Fetching Latest IOC, Getting Less Data

### ISSUE THREAD

**Issue by npormambi** [facebook/ThreatExchange#163]
Hello All,
 
I am trying to fetch latest IOC using TE, but getting very less data and on some queries no data at all.
https://graph.facebook.com/v2.8/threat_indicators?access_token=***|***&text=proxy&type=IP_ADDRESS
getting nothing.
Malicious URL  query provide hardly one result
https://graph.facebook.com/threat_descriptors?type=URI&status=MALICIOUS&since=a week ago&access_token=<access_token>e
How can I ask questions on facebook community or developer portal?

**Comment by mgoffin** [comment]
There is an ongoing issue with inaccurate result counts. For some reason you can perform the same query one after the other and you'll get less, more, or the same results as the previous run of the same query. There's several conversations about it in the Facebook group. You can make the problem slightly less troublesome by bumping the limit up to something like 1000, but it doesn't resolve the underlying problem.

The ThreatExchange team is currently working on a replacement of the backend system which is a very large task. I'm sure an update upon its completion will be provided in the Facebook group as well.

**Comment by npormambi** [comment]
@mgoffin  thanks for the update. 
Hope it will get sorted asap :)

**Comment by motiwarifacebook** [comment]
Thanks @mgoffin; your description is indeed correct. We're actively working on a fix and hoping to deploy it over the next few months.

Since this is a duplicate, closing.
