### ISSUE TITLE
Typo in main README.md

### ISSUE THREAD

**Issue by Fryyyyy** [facebook/ThreatExchange#166]
"ThreatExchanage" :)

**Comment by wxsBSD** [comment]
Can you please point to the specific typo? A quick look through the README.md shows it is using "ThreatExchange" in all the right places.

**Comment by Fryyyyy** [comment]
"There is also a reference user interface to ThreatExchanage, which is fully client-side, and written in Javascript!"

**Comment by juliannagler** [comment]
Thanks for the heads up, @Fryyyyy - fixed!

**Comment by wxsBSD** [comment]
Wow, I can't believe I missed that. I thought you were pointing at a capitalization problem. I didn't even see the spelling problem. To be fair, I was without coffee this morning. ;)

Thanks for pointing it out!

**Comment by Fryyyyy** [comment]
You're both welcome :)
