### ISSUE TITLE
[pdq] Helper for "lexicographically smallest" PDQ hash

### ISSUE THREAD

**Issue by Dcallies** [facebook/ThreatExchange#1676]
We want to experiment with ways to make PDQ lookup faster, especially as it pertains to looking up rotations.

One idea we had is to compute all of the 8 naive rotations (see #1665), but then only index the "lexicographically smallest" PDQ hash. 

Then, during lookup, you again only lookup the lexicographically smallest hash.

# Step 1: Simple PR
Add a method, which, given an image, returns only the lexicographically smallest hash

# Step 2: Proving This is a Good Idea
1. Find a large public listing of images, e.g. ImageNet - pick ~500-1000 of your favorite diverse set of images
2. First check the sanity of the dataset - find the distance at which you only match the items you are supposed to (default match distance is <32 hamming distance) - hash and brute force compare everything
3. Next make a set of the lexicographically smallest of your reference images, and repeat the experiment from #.2, you should still get the same result
4. Now, using a tool like ImageMagick, actually rotate some number of images (or all of them), and repeat the experiment using rotated images instead - you should still get the same result

# Step 3: Publish your results
We'll add a new section in the README for PDQ about this experiment, which includes your source dataset, the matching distance used, etc. We'll put it under a new section on "querying rotations"

# Step 4: Add a new binding
Head over to https://github.com/faustomorales/pdqhash-python and add an accessor for your new method that only returns the lexicographical smallest hash

# Step 5: Making the binding more functional with a CLI
This will be on https://github.com/faustomorales/pdqhash-python again. We want to add an installable CLI that will make it easier to debug PDQ. Check out #1169 

The cli should be named `pdq` and have the following behavior:
```
# Generates a hash
$ pdq file.png
facefacefacefacefacefaceface0111

$ pdq file.png --rotations
facefacefacefacefacefaceface0111
facefacefacefacefacefaceface0110
facefacefacefacefacefaceface0101
facefacefacefacefacefaceface0100
facefacefacefacefacefaceface0011
facefacefacefacefacefaceface0010
facefacefacefacefacefaceface0001
facefacefacefacefacefaceface0000

$ pdq file.png --smallest
facefacefacefacefacefaceface0000
```

**Comment by 16BitNarwhal** [comment]
After testing this approach, I found that it doesn’t work reliably. I wrote a Python script that first compares the Hamming distances between the calculated 8 dihedral hashes of an image and the 8 hashes of each rotation/flip of the same image. Observing that the Hamming distances between corresponding dihedral hashes of an image and its transformations tend to stay within the range [0, 30] suggests that PDQ dihedral hashing is fairly consistent across rotations and flips. However, this consistency doesn’t mean the hashes are identical; they only remain close enough to indicate similarity.

Next, I obtained the lexicographical minimum hash from each set of eight dihedral transformations for both the original image and its rotated/flipped versions. The goal was to find a "canonical" hash by selecting the smallest hash (lexicographically) from each set, ideally creating a unique identifier for any rotated or flipped version of the image. However, this approach proved unreliable.

For example, consider two transformations, A and B, of an original image, and let A' and B' represent the same transformations of a slightly modified version of the original image. Suppose their hashes (simplified to 5 bits, while PDQ hashes are actually 256 bits long) are:
```
A = [1, 0, 0, 0, 1], A' = [0, 0, 0, 0, 1] (1 bit difference)
B = [0, 1, 1, 1, 0], B' = [0, 1, 0, 1, 0] (1 bit difference)
```
If we select the lexicographical minimum, then:
```
min(A, B) = [0, 1, 1, 1, 0] (using B)
min(A', B') = [0, 0, 0, 0, 1] (using A')
```
Here, the minimal hashes differ by 4 out of 5 bits, simply because different minimal transformations were chosen (A vs. B). This inconsistency demonstrates that lexicographic minimization across dihedral transformations does not reliably produce a stable, rotation-invariant hash for matching purposes.

**Comment by 16BitNarwhal** [comment]
Here's the test script and it's output:
```python
import os
import cv2
from PIL import Image
import pdqhash
import numpy as np

BITS_IN_PDQ = 256

def simple_distance_binary(bin_a: str, bin_b: str) -> int:
    """
    Returns the Hamming distance of two binary strings.
    """
    assert len(bin_a) == BITS_IN_PDQ
    assert len(bin_b) == BITS_IN_PDQ
    return sum(bin_a[i] != bin_b[i] for i in range(BITS_IN_PDQ))

def hash_to_binary_string(hash_vector: np.ndarray) -> str:
    """
    Convert a binary vector to a binary string.
    """
    assert len(hash_vector) == BITS_IN_PDQ
    return "".join(str(int(x)) for x in hash_vector)

def simple_distance(hash_a: np.ndarray, hash_b: np.ndarray) -> int:
    """
    Returns the binary Hamming distance of two hash vectors.
    """
    return simple_distance_binary(hash_to_binary_string(hash_a), hash_to_binary_string(hash_b))

# Load and prepare the original image with various dihedral transformations
image_name = 'image7.jpg'
image_path = os.path.join('tests', 'images', image_name)
original_image = Image.open(image_path)

# Dihedral transformations of the image
original_images = [
    original_image,                                  # Original
    original_image.transpose(Image.ROTATE_90),      # 90° rotation
    original_image.transpose(Image.ROTATE_180),     # 180° rotation
    original_image.transpose(Image.ROTATE_270),     # 270° rotation
    original_image.transpose(Image.FLIP_TOP_BOTTOM), # Vertical flip
    original_image.transpose(Image.FLIP_LEFT_RIGHT), # Horizontal flip
    original_image.transpose(Image.FLIP_LEFT_RIGHT).transpose(Image.ROTATE_90),  # Horizontal flip + 90° rotation
    original_image.transpose(Image.FLIP_LEFT_RIGHT).transpose(Image.ROTATE_270)  # Horizontal flip + 270° rotation
]

def print_dihedral_distances(image):
    """
    Compute and print the Hamming distances between the dihedral hashes of the original image
    and the PDQ hash of each rotated/flipped version.
    """
    # Convert original image to array and compute all eight dihedral PDQ hashes
    arr = cv2.cvtColor(np.array(image), cv2.COLOR_RGB2BGR)
    hash_vectors = np.array(pdqhash.compute_dihedral(arr)[0])

    transformation_names = ["Original", "90° rotation", "180° rotation", "270° rotation", "Vertical flip", "Horizontal flip", "Horizontal flip + 90° rotation", "Horizontal flip + 270° rotation"]
    print("Hamming distances between dihedral hashes and rotated images:")
    for i, transformed_image in enumerate(original_images):
        transformed_arr = cv2.cvtColor(np.array(transformed_image), cv2.COLOR_RGB2BGR)
        hash_vector = pdqhash.compute(transformed_arr)[0]
        distance = simple_distance(hash_vectors[i], hash_vector)
        print(f"{transformation_names[i]}: Distance = {distance} bits")

def print_lex_min_distance(image):
    """
    Calculate and print Hamming distances using the lexicographically minimal hash across rotations.
    """
    # Compute the minimum hash of the original image across its dihedral hashes
    arr = cv2.cvtColor(np.array(image), cv2.COLOR_RGB2BGR)
    hash_vectors = np.array(pdqhash.compute_dihedral(arr)[0])
    min_dihedral_hash = hash_vectors[np.lexsort(hash_vectors.T[::-1])][0]

    print("Comparing lexicographically minimal hash:")
    for transformed_image in original_images:
        transformed_arr = cv2.cvtColor(np.array(transformed_image), cv2.COLOR_RGB2BGR)
        transformed_dihedral_hashes = np.array(pdqhash.compute_dihedral(transformed_arr)[0])
        min_transformed_hash = transformed_dihedral_hashes[np.lexsort(transformed_dihedral_hashes.T[::-1])][0]
        
        # Compute the distance between the minimum dihedral hash of the original and transformed image
        distance = simple_distance(min_dihedral_hash, min_transformed_hash)
        print(f"Distance to lex-min of transformed image: {distance} bits")

# Displaying results for explanation
print_dihedral_distances(original_image)
print_lex_min_distance(original_image)
```
Output:
```
Hamming distances between dihedral hashes and rotated images:
Original: Distance = 0 bits
90° rotation: Distance = 0 bits
180° rotation: Distance = 30 bits
270° rotation: Distance = 28 bits
Vertical flip: Distance = 28 bits
Horizontal flip: Distance = 0 bits
Horizontal flip + 90° rotation: Distance = 0 bits
Horizontal flip + 270° rotation: Distance = 30 bits

Comparing lexicographically minimal hash:
Distance to lex-min of transformed image: 0 bits
Distance to lex-min of transformed image: 0 bits
Distance to lex-min of transformed image: 134 bits
Distance to lex-min of transformed image: 134 bits
Distance to lex-min of transformed image: 134 bits
Distance to lex-min of transformed image: 0 bits
Distance to lex-min of transformed image: 0 bits
Distance to lex-min of transformed image: 134 bits
```
