### ISSUE TITLE
Support for timeout

### ISSUE THREAD

**Issue by joarleymoraes** [facebook/ThreatExchange#168]
Does the library support setting timeout for requests ?

**Comment by mgoffin** [comment]
It does not at this time. Is there a performance issue where you are in need of ensuring that requests timeout?

Generally the responses I've seen from ThreatExchange have been excellent and only increase with 1) The limit you set on your query (returning 5000 results takes longer than returning 500), and the amount of data returned (following `next` for 20000 items takes longer than 1000).

**Comment by joarleymoraes** [comment]
Yes, on FB side it's probably reliable. But on my server side, it might face some connectivity instability, and I don't some tasks hanging forever because of that.

**Comment by mshirley** [comment]
If there's no timeout the default is to sit and wait forever.  If the facebook api goes down we'd rather error with a timeout after 10 seconds than sit and wait forever.

**Comment by Dcallies** [comment]
Hey all, we're doing a bulk cleanup of the current state of the repo. By default we're closing all the old issues unless we're sure what the next steps are. Feel free to comment or re-open if this is still affecting you or you think something should happen.

```
               ...
             ;::::;
           ;::::; :;
         ;:::::'   :;
        ;:::::;     ;.
       ,:::::'       ;           OOO\
       ::::::;       ;          OOOOO\
       ;:::::;       ;         OOOOOOOO
      ,;::::::;     ;'         / OOOOOOO
    ;:::::::::`. ,,,;.        /  / DOOOOOO
  .';:::::::::::::::::;,     /  /     DOOOO
 ,::::::;::::::;;;;::::;,   /  /        DOOO
;`::::::`'::::::;;;::::: ,#/  /          DOOO
:`:::::::`;::::::;;::: ;::#  /            DOOO
::`:::::::`;:::::::: ;::::# /              DOO
`:`:::::::`;:::::: ;::::::#/               DOO
 :::`:::::::`;; ;:::::::::##                OO
 ::::`:::::::`;::::::::;:::#                OO
 `:::::`::::::::::::;'`:;::#                O
  `:::::`::::::::;' /  / `:#
   ::::::`:::::;'  /  /   `#
```
