### ISSUE TITLE
[pytx] Add ability to override ThreatExchange API version

### ISSUE THREAD

**Issue by hammem** [facebook/ThreatExchange#178]
Let's add some flexibility for sending queries/updates to different versions of the ThreatExchange API, without requiring a PR to support new versions and, alternatively, give folks a way to use an older version if they need to.

**Comment by mgoffin** [comment]
Is setting the value of the class attribute in the vocabulary not sufficient? That was my intention with the design at least.

**Comment by Dcallies** [comment]
Hey all, we're doing a bulk cleanup of the current state of the repo. By default we're closing all the old issues unless we're sure what the next steps are. Feel free to comment or re-open if this is still affecting you or you think something should happen.

```
               ...
             ;::::;
           ;::::; :;
         ;:::::'   :;
        ;:::::;     ;.
       ,:::::'       ;           OOO\
       ::::::;       ;          OOOOO\
       ;:::::;       ;         OOOOOOOO
      ,;::::::;     ;'         / OOOOOOO
    ;:::::::::`. ,,,;.        /  / DOOOOOO
  .';:::::::::::::::::;,     /  /     DOOOO
 ,::::::;::::::;;;;::::;,   /  /        DOOO
;`::::::`'::::::;;;::::: ,#/  /          DOOO
:`:::::::`;::::::;;::: ;::#  /            DOOO
::`:::::::`;:::::::: ;::::# /              DOO
`:`:::::::`;:::::: ;::::::#/               DOO
 :::`:::::::`;; ;:::::::::##                OO
 ::::`:::::::`;::::::::;:::#                OO
 `:::::`::::::::::::;'`:;::#                O
  `:::::`::::::::;' /  / `:#
   ::::::`:::::;'  /  /   `#
```
