### ISSUE TITLE
The pdq hashing for python version code is incomplete

### ISSUE THREAD

**Issue by 1994sugar** [facebook/ThreatExchange#185]

**Comment by johnkerl** [comment]
This is correct! We will address this. Thanks for the reminder task. :)

There is a pure-Python impl we can publish here; also, finish up the Python-to-C++ interface which is currently stubbed out in the repo.

**Comment by 1994sugar** [comment]
Thanks a lot!
Can I use the idea of pdq for the deduplication of other scenes?

**Comment by johnkerl** [comment]
@1994sugar what do you mean by "other scenes"?

**Comment by 1994sugar** [comment]
Thank you for your reply ! I am a student at school. The most recent research topic is how to remove the same mathematics assignments image or similar math assignments image.

**Comment by 1994sugar** [comment]
I am trying to use the phash algorithm and found that it's not suitable for text images, and often makes mistakes.

**Comment by johnkerl** [comment]
I see. PDQ is not likely to do well with dense text either. It downsamples to 64x64 greyscale before doing other math, and fine details will get lost.

**Comment by 1994sugar** [comment]
I agree with you. Do you know any way to solve this problem? Thanks a lot. 

发自我的iPhone

------------------ Original ------------------

**Comment by johnkerl** [comment]
Using OCR perhaps?

**Comment by 1994sugar** [comment]
Thank for your help, I will try it

**Comment by computermacgyver** [comment]
> There is a pure-Python impl we can publish here; also, finish up the Python-to-C++ interface which is currently stubbed out in the repo.

@johnkerl The pure-python implementation would be great for teaching. Any chance this can be made available relatively quickly?

**Comment by johnkerl** [comment]
@computermacgyver I'm in contact with the individual who did the Python port & we should be able to do this. I'll be in touch soon. Thanks for the interest!! :)

**Comment by johnkerl** [comment]
Hi @computermacgyver the pure-Python implementation is in place at https://github.com/facebook/ThreatExchange/pull/205 -- merged to HEAD just now.

**Comment by johnkerl** [comment]
The C++-to-Python interface is next up

**Comment by computermacgyver** [comment]
Thank you, @johnkerl ! I really appreciate it.

**Comment by D3MZ** [comment]
`../../data/bridge-mods/*g` does not exist btw. Can you include it in the repo so we can experiment quickly please. 

from your python readme 
`$ python ./pdqhashing/tools/pdq_photo_hasher_tool.py --pdq ../../data/bridge-mods/*g`

**Comment by Dcallies** [comment]
Hey all, we're doing a bulk cleanup of the current state of the repo. By default we're closing all the old issues unless we're sure what the next steps are. Feel free to comment or re-open if this is still affecting you or you think something should happen.

```
               ...
             ;::::;
           ;::::; :;
         ;:::::'   :;
        ;:::::;     ;.
       ,:::::'       ;           OOO\
       ::::::;       ;          OOOOO\
       ;:::::;       ;         OOOOOOOO
      ,;::::::;     ;'         / OOOOOOO
    ;:::::::::`. ,,,;.        /  / DOOOOOO
  .';:::::::::::::::::;,     /  /     DOOOO
 ,::::::;::::::;;;;::::;,   /  /        DOOO
;`::::::`'::::::;;;::::: ,#/  /          DOOO
:`:::::::`;::::::;;::: ;::#  /            DOOO
::`:::::::`;:::::::: ;::::# /              DOO
`:`:::::::`;:::::: ;::::::#/               DOO
 :::`:::::::`;; ;:::::::::##                OO
 ::::`:::::::`;::::::::;:::#                OO
 `:::::`::::::::::::;'`:;::#                O
  `:::::`::::::::;' /  / `:#
   ::::::`:::::;'  /  /   `#
```
