### ISSUE TITLE
[Error] no matching function for call to'getline (ch) Ar**, size_t*, FILE*)'

### ISSUE THREAD

**Issue by Yisu123** [facebook/ThreatExchange#189]
Excuse me, when I implemented PDQ by CPP , I found that in pdq-photo-hasher.cpp there seemed to be no getline namespace (line 125). When I used "std:: getline (& filename, & linelen, stdin)" to solve this problem, I met [Error] no matching function for call to'getline (ch) Ar**, size_t*, FILE*)',Do you know any way to solve this problem?Thank you.

**Comment by johnkerl** [comment]
What is your compiler version? E.g. `g++ --version`.

**Comment by johnkerl** [comment]
FYI, this should be `getline` from `stdio.h` not `std::getline` (which involves `iostream`).

**Comment by johnkerl** [comment]
Can you please share the compiler output you saw from "there seemed to be no getline namespace (line 125)", before changing from `getline` to `std::getline`?

**Comment by Yisu123** [comment]
Thank you very much for your reply. I've solved this problem, probably because I compiled it on Windows and lacked some necessary libraries. When I compiled it in linux, I didn't find this error. so I think it may be a problem of my computer environment. I'm sorry to disturb you.

**Comment by johnkerl** [comment]
No worries -- thank you! :)
