### ISSUE TITLE
Hashes for text similar to pdq for images

### ISSUE THREAD

**Issue by bbhopesh** [facebook/ThreatExchange#195]
Hi guys, I was just wondering what algorithms do you use for creating hash of known fake news text inside your newsroom? Something equivalent of PDQ that you use for text. The hash should be able to tolerate slight variations in words/synonyms etc.

**Comment by Dcallies** [comment]
Hey @bbhopesh, I recently did some work that might address this. Check it out: https://github.com/facebook/ThreatExchange/pull/277
