### ISSUE TITLE
Error unmarshaling json, ThreatDescriptor.expired_on

### ISSUE THREAD

**Issue by mshirley** [facebook/ThreatExchange#196]
https://github.com/facebook/ThreatExchange/blob/06806faa683a14417e31d93657ed3bc33b10a460/golang/threatexchange/threatexchange.go#L97

ExpiredOn should be a string instead of an int, otherwise i'm getting unmarshaling errors.

`cannot unmarshal string into Go struct field ThreatDescriptor.expired_on of type int`

the expired_on fields are now string dates `"expired_on":"2019-09-20T00:00:00+0000"`

**Comment by bodnarbm** [comment]
Thanks for reporting this, @mshirley! Apologies for the delay in getting that fixed.
