### ISSUE TITLE
TMK integration with FAISS

### ISSUE THREAD

**Issue by bbhopesh** [facebook/ThreatExchange#197]
README.md says that integration has been successfully prototyped and information will be posted soon. Can you please give more information about integration with FAISS? We are using TMK in one of our applications and we need an efficient way of querying.

**Comment by bbhopesh** [comment]
Hey @johnkerl, now that I can compile `tmk-query-with-faiss`, I am running into some issues while running it. It fails with FaissException. It seems to be some error because of way faiss works. Below is the error snapshot. Can you please take a look?

![image](https://user-images.githubusercontent.com/8807496/64060487-0ca77980-cb82-11e9-8148-bbc758c1fa95.png)

**Comment by johnkerl** [comment]
@bbhopesh I checked with the FAISS maintainers & it turns out we should transparently fall back to linear search for small-sized datasets. Using FAISS when the sizes are big enough to be useful. This would take a wrapper method.

**Comment by bbhopesh** [comment]
If it's not lot of work, can you please write that wrapper function? I don't know details of FAISS to implement it correctly.

**Comment by johnkerl** [comment]
No worries, we can do so! :)

**Comment by johnkerl** [comment]
I don't know FAISS well either but it would be the current guts of `tmk-query.cpp` whenever the current guts of `tmk-query-with-faiss.cpp` fails due to sizing issues.

**Comment by kenkyusha** [comment]
has anybody made reasonable guide how this should be set up from scratch?
I did clone this repo and ran into the problem saying *faiss* is missing.
After cloning faiss ran into the issue of not having OpenMP running properly.
Luckily this was quick fix just adapting the g++ in the makefile.inc to the one which works with fopenMP, the faiss compiles and installes (lots of warning in the log).
And now I am trying to build the TMK again and get following:
*using the g++ working with fopenmp*
ld: unknown option: -rpath=/usr/local/lib
collect2: error: ld returned 1 exit status
make: *** [tmk-query-with-faiss] Error 1

*using the default one*:
ld: unknown option: -rpath=/usr/local/lib
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [tmk-query-with-faiss] Error 1

any hints would be helpful :-)

**Comment by johnkerl** [comment]
@kenkyusha thanks, this definitely needs a write-up. :^/

My team is having a heavy conference month & I hope we can get to this very very soon.

**Comment by kenkyusha** [comment]
> @kenkyusha thanks, this definitely needs a write-up. :^/
> 
> My team is having a heavy conference month & I hope we can get to this very very soon.

Try it out on Ubuntu system, there it works well

**Comment by yfq512** [comment]
> I tried using `tmk-query-with-faiss` but I faced issues with includes like wrong relative paths etc. Please let me know when you are done integrating with Makefile. It will be very useful feature for us.

@bbhopesh , I face the same issues with you, I do't know how to make `tmk-query-with-faiss`. Can you show your methods?
