### ISSUE TITLE
Minor document optimization

### ISSUE THREAD

**Issue by Avagenzo** [facebook/ThreatExchange#200]
Until chapter "Look for duplicates within sample videos" i had no difficulties following the README. But at one point bash commands don't start with "./" anymore. For Linux newbies the commands in the description won't work if its copied to the terminal.

For clarification: 
Actual state: 
`tmk-clusterize --c1 0.7 --c2 0.7 -s *.tmk`

Target state:
`./tmk-clusterize --c1 0.7 --c2 0.7 -s *.tmk`

**Comment by johnkerl** [comment]
Thanks for the catch! Bad habit of mine to leave out the `./` :^/

**Comment by mounikabodapati** [comment]
Fixed it!
