### ISSUE TITLE
tmk-query fails

### ISSUE THREAD

**Issue by Avagenzo** [facebook/ThreatExchange#206]
Following along the README i found that tmk-query doesn't work. Querying the sample-hashes with 

`./tmk-query --c1 0.7 --c2 0.7 ../sample-hashes/needles.txt
 ../sample-hashes/haystack.txt | sort -n`

gives me the following error:
```
fopen: No such file or directory
./tmk-query: could not open "chair-orig-22-hd-no-bar.tmk" for read.
./tmk-query: failed to read "chair-orig-22-hd-no-bar.tmk".
```

I already checked read permissions for the file, which looks fine to me: 
`-rwxr-xr-x 1 root root 263344 Aug 29 15:53 chair-orig-22-hd-no-bar.tmk`

Is there a way around this error?

**Comment by johnkerl** [comment]
The paths within the `.txt` files should be accessible by from where the `tmk-query` is running which is `.`. So, a few options are:

* `cd ../sample-hashes` and then `../cpp/tmk-query ...`
* Edit the `.txt` files to include relative paths e.g. `../sample-hashes/chair-orig-22-hd-no-bar.tmk`
* Edit the ` .txt` files to include absolute paths e.g.  `/path/to/sample-hashes/chair-orig-22-hd-no-bar.tmk`

**Comment by johnkerl** [comment]
In the `README.md` I used the third option (`find /path/to/hashes -name '*.tmk' > needles.txt`) but I could have been more clear what happens if you don't.

**Comment by johnkerl** [comment]
Updated https://github.com/facebook/ThreatExchange/blob/master/hashing/tmk/README.md -- thank you! :)

**Comment by johnkerl** [comment]
Please let me know if this task needs to be re-opened.

**Comment by Avagenzo** [comment]
Thank you for making this clearer. It works fabulous. Issue can be closed.
