### ISSUE TITLE
python version pdq is slow 

### ISSUE THREAD

**Issue by Usernamezhx** [facebook/ThreatExchange#209]
thanks for your work. when i test the pdq. it is very slow about 1.5s  per image size:1440 x 1440.  this is my test code:
```python
def get_pdq(path):
    hashingMetadata = PDQHasher.HashingMetadata()
    hashAndQuality = pdqHasher.fromFile(path, hashingMetadata)
    hash = hashAndQuality.getHash()
    return hash
if __name__ == '__main__':
    pdqHasher = PDQHasher()
    q1 = get_pdq(img_file1)
    q2 = get_pdq(img_file2)
    dis = q1.hammingDistance(q2)
```

**Comment by johnkerl** [comment]
In our reference design we recommend initial size reduction to 512x512:

https://github.com/facebook/ThreatExchange/blob/master/hashing/pdq/python/pdqhashing/hasher/pdq_hasher.py#L83

That should help a lot.

Also, we still need to publish the Python-C++ integrated version which should help even more.
