### ISSUE TITLE
Comment leads to a dead link

### ISSUE THREAD

**Issue by D3MZ** [facebook/ThreatExchange#213]
https://github.com/facebook/ThreatExchange/blob/00f9c140360fd6189e2be7de4ad680d474cbeebb/hashing/pdq/python/pdqhashing/types/hash256.py#L12

**Comment by johnkerl** [comment]
Thanks, good catch! Will fix :)

**Comment by johnkerl** [comment]
Hi @D3MZ -- really really really sorry about the long delay. :(

This is fixed in https://github.com/facebook/ThreatExchange/commit/a9d9020c9a912fbedb60a804d3bc3ca8f5c46784.

**Comment by johnkerl** [comment]
Please let us know if we need to reopen -- thanks!
