### ISSUE TITLE
PDQ, but for triangles

### ISSUE THREAD

**Issue by DonaldTsang** [facebook/ThreatExchange#216]
I have seen an image matching engine that uses triangular mesh to find similar images
https://pippy360.github.io/transformationInvariantImageSearch
Is it possible to modify PDQ's algorithm to allow images of equilateral triangles to be converted into hashes for easy matching?
See https://github.com/thorn-oss/perception/issues/6 and https://github.com/pippy360/transformationInvariantImageSearch/issues/4

**Comment by Dcallies** [comment]
Hey all, we're doing a bulk cleanup of the current state of the repo. By default we're closing all the old issues unless we're sure what the next steps are. Feel free to comment or re-open if this is still affecting you or you think something should happen.

               ...
             ;::::;
           ;::::; :;
         ;:::::'   :;
        ;:::::;     ;.
       ,:::::'       ;           OOO\
       ::::::;       ;          OOOOO\
       ;:::::;       ;         OOOOOOOO
      ,;::::::;     ;'         / OOOOOOO
    ;:::::::::`. ,,,;.        /  / DOOOOOO
  .';:::::::::::::::::;,     /  /     DOOOO
 ,::::::;::::::;;;;::::;,   /  /        DOOO
;`::::::`'::::::;;;::::: ,#/  /          DOOO
:`:::::::`;::::::;;::: ;::#  /            DOOO
::`:::::::`;:::::::: ;::::# /              DOO
`:`:::::::`;:::::: ;::::::#/               DOO
 :::`:::::::`;; ;:::::::::##                OO
 ::::`:::::::`;::::::::;:::#                OO
 `:::::`::::::::::::;'`:;::#                O
  `:::::`::::::::;' /  / `:#
   ::::::`:::::;'  /  /   `#
