### ISSUE TITLE
How to use this code?

### ISSUE THREAD

**Issue by Janezzliu** [facebook/ThreatExchange#217]
How to use this code to comput the similarity of two images? It's there any documentation? I wanna to delete the similar pictures.

**Comment by Dcallies** [comment]
Hey @Janezzliu!

Thanks for checking us out! There's some documentation in the various README sections in the project. 

Here's some starter places to check out:
- https://github.com/facebook/ThreatExchange/blob/master/README.md
- https://github.com/facebook/ThreatExchange/blob/master/hashing/README.md
- https://github.com/facebook/ThreatExchange/blob/master/hashing/hashing.pdf

Specifically for generating hashes for photos and looking at similar "clusters", you can check out a java implementation here: https://github.com/facebook/ThreatExchange/tree/master/hashing/pdq/java

I can give you some more specific advice depending on where the similar pictures you want to delete live.

**Comment by jcohenho** [comment]
@Dcallies I have a couple questions about the hashing steps and the examples. 

1. Do you have more details on the sample videos provided? Are all the sample videos of the same kind supposed to successfully match with one another? i.e. are the chair videos all supposed to have a TMK match with one another? When I run `./tmk-compare-two-tmks chair-orig-22-sd-bar.tmk ../sample-hashes/chair-orig-22-hd-no-bar.tmk` the files do not match in this case. 
2.  Is the `./tmk-compare-two-tmks` step computing the level-1 feature for the unweighted average over all frame features?

**Comment by johnkerl** [comment]
Hi @jcohenho -- there's some information (albeit brief) in the [hashing/tmk/README-more.md](https://github.com/facebook/ThreatExchange/blob/master/hashing/tmk/README-more.md) -- the `tmk-compare-two-tmks` is not intended for video-matching between potential variations of a video -- see `tmk-query` for that. Rather, it's intended for comparing hashes of the exact same video, for regressions or portability concerns. It goes through each of the feature vectors and compares them (pairwise between the two `.tmk` files) within a tolerance. https://github.com/facebook/ThreatExchange/commit/40f391da07a29c0d5cd5162d1d4bbbb903fdcb39 should help to clarify a little.

I think you want `tmk-two-level-score` ... but this question points out that we don't have a neat mapping from `(file1, file2, thresholds) -> {pass,fail}`. :^/

**Comment by jcohenho** [comment]
@johnkerl Thanks so much. I removed my comment to post in a new issue, but then after running a make and following the README I was able to understand the difference. I was able to get a score of over 0.7 comparing different variations of my own video, which is really exciting!
