### ISSUE TITLE
Is it possible to enable GPU-faiss for tmk-query-with-faiss? 

### ISSUE THREAD

**Issue by shirleyH-canva** [facebook/ThreatExchange#218]
Is it possible to enable faiss on the GPU for `tmk-query-with-faiss`? 
Given that GPU faiss could provide acceleration on queries.

**Comment by johnkerl** [comment]
nice, thanks! :)

**Comment by shirleyH-canva** [comment]
Is the GPU version under development? 
If not, is it possible to modify the current `tmk-query-with-faiss` to achieve such purpose?

**Comment by johnkerl** [comment]
Hi @shirleyH-canva -- I think I can find some people within Facebook who know how to do this, and possibly contribute it back to this repo. This is on my task list for the near future.

**Comment by Avagenzo** [comment]
@johnkerl I know this is 2 years now, but is there any news on the gpu enablement? Thanks!

**Comment by johnkerl** [comment]
Hi @Avagenzo -- sorry, I'm not involved with this project as of a year and a half now.

Perhaps check with any recent committers to https://github.com/facebook/ThreatExchange -- ? Sorry I can't be of more help. :(

**Comment by Avagenzo** [comment]
@johnkerl No worries. Thank you for the hint! @BarrettOlson @schatten Do you guys have any news regarding gpu support here?

**Comment by schatten** [comment]
Hi @Avagenzo. At this point, we are not looking at enhancements to TMK. 

We would be happy to shepherd a pull-request, though.
