### ISSUE TITLE
about the input resize

### ISSUE THREAD

**Issue by Usernamezhx** [facebook/ThreatExchange#223]
thanks for your work. I notice that the python version pdq use the thumbnail function to resize the image. but in c++ version pdq. first of all. check if height or width is larger than the 512. if True. then resize the input to (512, 512). what is the performance different between them? thanks in advance.

**Comment by johnkerl** [comment]
PDQ's tent-filter downsampler is too slow on full-sized input but works the same in any language/platform. So:

* Using PDQ's tent-filter downsampler to get from full resolution down to 64x64 was too slow for higher-resolution images
* Using implementation-specific fastest-available downsampler (e.g. the Python thumbnail function) to get all the way to 64x64 is fast, but, resulted in more hamming bits of distance between various PDQ implementations (e.g. Python vs C++)
* Using fastest-available downsampler to get to 512x512, then the tent-filter to get to 64x64 was a good compromise which was fast, and also had smaller hamming distance between various PDQ implementations (2,4,6 bits if I recall correctly).

I hope that helps! I'll write this up in the docs as well.

**Comment by Usernamezhx** [comment]
thanks for you reply.

**Comment by johnkerl** [comment]
I updated page 10 of `hashing.pdf` on https://github.com/facebook/ThreatExchange/commit/8c12d1baa6972a4b81d8a1a3bc51c0b90343bc3b

@Usernamezhx thanks for the question! :)
