### ISSUE TITLE
missing ./tmk-two-level-score file 

### ISSUE THREAD

**Issue by jcohenho** [facebook/ThreatExchange#225]
Hello! I've made it to the step where I need to look at all pair-scores, however I cannot find the .tmk-two-level-score file. 
After running 
```
$ cd cpp
$ make
```
I can only see 
```
./tmk-clusterize
./tmk-compare-two-tmks
./tmk-hash-video
./tmk-query
./tmk-show-pair-offsets
./tmkdump
```
Is there something I'm missing?

**Comment by johnkerl** [comment]
Hmm, this is weird. What's the parent directory of your `cd cpp`?

The source file is [here](https://github.com/facebook/ThreatExchange/blob/master/hashing/tmk/cpp/bin/tmk-two-level-score.cpp) and it's referenced in the `hashing/tmk/cpp/Makefile` [here](https://github.com/facebook/ThreatExchange/blob/master/hashing/tmk/cpp/Makefile#L56) ...

**Comment by jcohenho** [comment]
My full path is `ThreatExchange/hashing/tmk/cpp`. When I try running `make` from here now, I get `fatal error: 'IndexIVFPQ.h' file not found`. FYI I'm on mac OS 10.15.3.

**Comment by johnkerl** [comment]
Ah, sorry about that. Let me put up a change. (That's a remnant of incomplete work on https://github.com/facebook/ThreatExchange/issues/197 -- my apologies.)

**Comment by johnkerl** [comment]
https://github.com/facebook/ThreatExchange/commit/0eac5ba47cd87116a0129f4ddb2cb1e51d0254ca fixes this.

**Comment by jcohenho** [comment]
@johnkerl thank you! I can successfully run `make` and I now see the ./tmk-two-level-score file now.

**Comment by johnkerl** [comment]
Sorry about that @jcohenho and thanks!! :)
