### ISSUE TITLE
Allow pytx to read creds from a file

### ISSUE THREAD

**Issue by ivanlei** [facebook/ThreatExchange#27]
Rather than having to modify scripts, pytx could read the necesary creds from a file or environment var, like boto does.

**Comment by mgoffin** [comment]
So how about something like this:

```python
from pytx import init

# Looks for ENV variables. If it finds TX_ACCESS_TOKEN
# it will use it as-is. If it finds TX_APP_ID and TX_APP_SECRET
# it will combine them and use them.
init()

# Looks for the file passed in as token_file and reads it.
# If it finds one line, it will assume it is the access token and use it.
# If it finds two lines, it will combine them and use them.
init(token_file="foo")

# Uses the passed in app_id and app_secret to combine into the token.
init(app_id="foo", app_secret="bar")
```

**Comment by jessek** [comment]
Does https://github.com/facebook/ThreatExchange/pull/28 solve this?

**Comment by mgoffin** [comment]
Yep!

**Comment by omercnet** [comment]
Oretty important feature imo, deserves a version bump.
Please create a tag for v0.1.3 to match https://pypi.python.org/pypi/pytx

**Comment by mgoffin** [comment]
Why is 0.1.2 gone from PyPi already? Wouldn't 0.1.3 just be another new version?

**Comment by omercnet** [comment]
not sure I understand your question
0.1.2 is here https://pypi.python.org/pypi?:action=display&name=pytx&version=0.1.2

**Comment by mgoffin** [comment]
If I go to https://pypi.python.org/pypi/pytx I only see 0.1.3. If I search for "pytx" it shows me 0.1.2 with a link to 0.1.3.

What I was hoping for is to see all of the versions in the downloads list, but I guess as long as someone can still do `pip install pytx==0.1.2` then we're fine :)

**Comment by omercnet** [comment]
yea, pypi doesn't keep all the versions in one place publicly - but you can still install old versions like that

**Comment by omercnet** [comment]
ah, look at https://pypi.python.org/pypi/pytx now
not sure why the search send you to 0.1.2 by default - maybe their indexes takes a while to update

**Comment by mgoffin** [comment]
Ahh there we go!
