### ISSUE TITLE
Don't remove old versions of pytx from pypi

### ISSUE THREAD

**Issue by davemarchevsky** [facebook/ThreatExchange#29]
`pytx` is awesome and we've started using it to talk to ThreatExchange at Bitly. We had pinned our `pytx` version to `0.1.0`, which is no longer available in pypi.

I propose keeping older versions in pypi unless there's a security hole or other glaring need to remove. Of course, the ThreatExchange API might change to a degree such that older versions of `pytx` aren't useful. Not sure what to do in that case.

Thanks!

**Comment by mgoffin** [comment]
Hmm. Not sure how that works but we never released pytx on PyPi before 0.1.2 was accepted.

I agree though that it should keep all of the versions as they go forward! Thanks for pointing this out I might not have noticed :)

**Comment by davemarchevsky** [comment]
That's odd - there was a `0.1.0` release on pypi at some point. Oh well.

I consider this sufficiently addressed :).

**Comment by omercnet** [comment]
there's an odd issue in PyPi that doesn't let you replace versions, I had accidentally uploaded a broken version and couldn't replace it, so now it's gone.

 I'm trying to plug pypi with travis to make sure only valid commits gets uploaded to pip, stay tuned :)
