### ISSUE TITLE
how to compute the simility between two pictures

### ISSUE THREAD

**Issue by wongdu** [facebook/ThreatExchange#301]
after git clone the source code, i "cd" to "ThreatExchange/pdq/cpp" direcotry,
then run the "make" command,and i got the "pdq-photo-hasher" executable file.
but when run the "./pdq-photo-hasher ../data/reg-test-input/dih/bridge-1-original.jpg",
i got the error infomation："
[CImg] *** CImgIOException *** [instance(0,0,0,0,(nil),non-shared)] CImg<unsigned char>::load(): Failed to recognize format of file '../data/reg-test-input/dih/bridge-1-original.jpg'.
0000000000000000000000000000000000000000000000000000000000000000,-85242560,../data/reg-test-input/dih/bridge-1-original.jpg"

i just want to get the simility of two pictures, a metric score is better.any advice is grateful.

**Comment by wongdu** [comment]
when run the “./pdq-photo-hasher” command,and got tips “Usage: ./pdq-photo-hasher [options] {one or more filenames}
Supported filetypes are JPEG and PNG”,only JPEG and PNG are supported?

**Comment by wongdu** [comment]
i tried with a jpeg file,but still got nothing but bellow information
“
[CImg] *** CImgIOException *** [instance(0,0,0,0,(nil),non-shared)] CImg<unsigned char>::load(): Failed to recognize format of file '../data/reg-test-input/dih/pexels-photo-4983110.jpeg'.
0000000000000000000000000000000000000000000000000000000000000000,-821073664,../data/reg-test-input/dih/pexels-photo-4983110.jpeg”

**Comment by wongdu** [comment]
is there a simple way to get the simility of two pictures? any advice is grateful.

**Comment by wongdu** [comment]
after download a PNG file from the internet,then tried with it ,but still cannot get the hash value
“
[CImg] *** CImgIOException *** [instance(0,0,0,0,(nil),non-shared)] CImg<unsigned char>::load(): Failed to recognize format of file '../data/reg-test-input/dih/cpp.PNG'.
0000000000000000000000000000000000000000000000000000000000000000,-1862085008,../data/reg-test-input/dih/cpp.PNG”

**Comment by bodnarbm** [comment]
Hi @wongdu,

I see a couple of different questions across the various comments. I'll attempt to address all of them here, but please let me know if I missed anything.

1. **Regarding the `CImgIOException`s you are seeing running `./pdq-photo-hasher`**

Based on the exception and the output hash that it is reporting of all 0's, I suggest installing ImageMagick on the machine that is running `./pdq-photo-hasher`. The CImg library used by that tool offloads the processing of compressed file formats like JPG and PNG to other tools like ImageMagick. While CImg works with a variety of other options, based on how `pdq-photo-hasher` is built in the Makefile, using ImageMagick has typically gotten rid of this issue for us. Once you have ImageMagick installed, you can rerun the `make` and if you run `make run-reg-test` it should give you a PASSED result. Instructions on installing ImageMagick vary by OS, but there should be good instructions on their site at https://imagemagick.org/ for each OS.

2. **Regarding supported filetypes**

Right now, yes, JPG and PNG are the only supported file types for that tool (`pdq-photo-hasher`). Other uncompressed filetypes may work with CImg, but I have not tried them. Same, with other compressed image file types may work, but I have not tried them.

That said, the underlying PDQ hashing algorithm implemented in `hashing/pdqhashing.h` does the hashing based on decomposed image data, and thus the algorithm itself should work with other image formats provided there is some image processor to understand that image data.

3. **Regarding how to compare the hashes once you have them**
 
The [hashing paper](https://github.com/facebook/ThreatExchange/blob/b8689cd5dd9c9292d28f1850244d1526c5f9dd1b/hashing/hashing.pdf) talks about this in greater detail, but comparing the similarity between two PDQ hashes involves computing the hamming distance of the 256-bits that the hashes represent and then comparing that to some threshold value you choose. Hashes with hamming distance below that threshold value are considered similar. The smaller the threshold value you choose, the more alike the images need to be to be considered similar. The hashing paper points out that thresholds around 10, 20, and 30 have given good confidence in testing datasets and the paper itself uses a threshold of 32 for it's examples.

There is a binary tool provided in this repo called `mih-query` that does this matching using the MIH indexing technique. For that tool, you pass it a needles file containing the hashes you want to query to find similar hashes of and a haystack file containing the hashes you want to search against. You can test this with data within this repo using something like

`./mih-query -d 32 ../data/reg-test-input/needles.txt ../data/reg-test-input/haystack.txt`

**Comment by wongdu** [comment]
@bodnarbm ,thank you so much!
my bad ,i didnot read the readme file carefully.
that you comment is very helpful!
after run the "yum install ImageMagick" command on centos7, i run the "./pdq-photo-hasher" and got a good hash string.
when run the "./mih-query" executable file, i got the similarity.
