### ISSUE TITLE
duplicated python scripts are confusing

### ISSUE THREAD

**Issue by ivanlei** [facebook/ThreatExchange#34]
``` shell
[ivanlei@some_machine:~/source/ThreatExchange] $ find . -name 'get_*.py'
./malware/get_samples.py
./members/get_members.py
./pytx/scripts/get_compromised_credentials.py
./pytx/scripts/get_indicators.py
./pytx/scripts/get_members.py
./threat_indicators/get_compromised_credentials.py
./threat_indicators/get_indicators.py
```

So there's:
- 2 copies of `get_compromised_credentials.py`
- 2 copies of `get_indicators.py` 

and there's basically 4 directories with scripts in them:
- `malware/`
- `members/`
- `pytx/scripts/`
- `threat_indicators/`

I suggest all the scripts be moved into `pytx/scripts/` so they can be installed with as part of the `pytx` python package.

**Comment by mgoffin** [comment]
When I wrote pytx originally I duplicated the scripts that existed and put them in `pytx/scripts`. Then I rewrote them using pytx with a goal of replacing the originals. This would help do that but I think the ones in `pytx/scripts` need some updating to have feature-parity before the others could go away.

**Comment by omercnet** [comment]
I agree, I was also working on fixing the scripts so that they work out of the box, by removing the app-id/secret vars and defaulting to the new ENV vars

**Comment by hammem** [comment]
+1  @tpott, any opposition to us merging your scripts into pytx?

**Comment by jessek** [comment]
@tpott is offline for the next two weeks. But being the guy who is ultimately responsible for maintaining this, fewer copies of the same code is better. Let's make these scripts work out of the box using the environment variables.

**Comment by tpott** [comment]
Just saw this thread! I'm willing to refactor these a bit. My original thought for these were that (1) pytx didn't exist at the time, but also (2) serve as a vanilla python example (as in there were no required libs).

So I could either refactor these completely into pytx, at which point there won't be any standalone demo python, or just clean them up and create a scripts directory to move these to. Thoughts/preferences?

**Comment by hammem** [comment]
Fold them into pytx!

**Comment by mgoffin** [comment]
I apologize. I really need to find time to update pytx to use descriptors :(

**Comment by mgoffin** [comment]
pytx is all updated. moving the scripts into pytx (which might just mean updating the ones that are already there) will be a good test for the new code to iron out any bugs.

**Comment by jessek** [comment]
@mgoffin Can we close this out?

**Comment by mgoffin** [comment]
I don't believe all of the scripts have been moved over and removed from their current location.

I still see scripts in the `malware`, `members`, and `threat_indicators` folder which don't use pytx and I'm not sure if there's feature parity with anything in the `pytx/scripts` folder. There are also several scripts in the `get_all_data` folder which do use pytx, but aren't in the `pytx/scripts` folder.

**Comment by Dcallies** [comment]
This issue has staled out, and we've just do a big cleanup of the existing files. malware, members, and a few others are now gone. Various python scripts still exist in api-reference-examples/python/ but hopefully they are not duplicated.
