### ISSUE TITLE
[hasher-matcher-actioner] Implement fetch/sync module

### ISSUE THREAD

**Issue by Dcallies** [facebook/ThreatExchange#365]
The HMA prototype has the key failing that you have to put the hashes into the s3 bucket to get it work, when it could just easily fetch its own hashes. 

Facebook people, the internal task for this is: T82242396

This should probably happen after: https://github.com/facebook/ThreatExchange/issues/364

**Comment by schatten** [comment]
[Cleanup] This is now complete.
