### ISSUE TITLE
Github hook for ReadTheDocs

### ISSUE THREAD

**Issue by mgoffin** [facebook/ThreatExchange#37]
pytx is setup on readthedocs (pytx.readthedocs.org) but in order for it to kick off a new build it needs to be notified (they don't seem to rebuild on their own).

There are ways to hook Github into readthedocs: https://docs.readthedocs.org/en/latest/webhooks.html

readthedocs gives me the following post-commit hook:

```
curl -X POST http://readthedocs.org/build/pytx
```

I am not sure how the ReadTheDocs Github app works with the above directions, but it would make life a lot easier knowing when a commit makes it to master the docs are rebuilt automagically :)

**Comment by hammem** [comment]
@mgoffin, sorry this is taking so long.  I should have the webhook added shortly.

**Comment by mgoffin** [comment]
No worries :)

**Comment by hammem** [comment]
ok, @mgoffin , the commit hook should be there now.  can you confirm it's working?  I'm a readthedocs n00b, so can't really tell if it's doing it.

**Comment by mgoffin** [comment]
No worries :) I'll keep an eye out the next time a commit hits the repo and see if it kicks off a build!

**Comment by jessek** [comment]
Is this working now?

**Comment by mgoffin** [comment]
Just got to looking. Last build was 2 months ago it looks like.

**Comment by hammem** [comment]
Looks like this is working now.  @mgoffin, ok to close this one out?

**Comment by mgoffin** [comment]
It's not working, I had to manually build it last time. But that's fine. I think it'll be low-overhead for me to manually kick off a build every time we make a major change :)

**Comment by jessek** [comment]
@mgoffin Did we ever get this fixed? Is it worth doing?

**Comment by mgoffin** [comment]
@jessek It's not working, but given how new releases work it's just another small step for me to rebuild it. I'll close this out :) Thanks!
