### ISSUE TITLE
object "type" field only included in metadata

### ISSUE THREAD

**Issue by mgoffin** [facebook/ThreatExchange#38]
I had this conversation with @jessek, @mrichard91, and @hammem, but I don't think we got anywhere.

The API allows you to query a specific object by identifier. The URL looks something like this:

```
https://graph.facebook.com/<object-id>
```

With the above context it is unknown to the person querying the API what `type` of object is going to be in the response. One could add `?metadata=1` to the query which will bloat the response with a ton of extra information about each field and what it means, as well as the object's `type`.

From a development standpoint this becomes a bit cumbersome. Specifically in `pytx` it causes a bit of a problem when querying for details of an object as can be found here:

https://github.com/facebook/ThreatExchange/blob/master/pytx/pytx/common.py#L209

Users have run into situations where they felt that `pytx` was "stripping" fields out of the response. This looked like the case because they were filling one class with the fields from another so only the common fields were being applied.

There is the issue that a `ThreatIndicator` has a `type` field already, so adding the object's `type` field would clobber the name, but I still recommend adding a field somewhere which denotes the type of object a developer is working with. In many cases context will prevail (ex: I queried `/threat_indicators` so I'm getting `ThreatIndicator` objects back) but there are many cases where it won't and an automated system needs to determine what it's working with.

**Comment by jessek** [comment]
We could add a field, object_type, which indicated the type of object being retrieved. The values would be: THREAT_DESCRIPTOR, THREAT_INDICATOR, MALWARE_FAMILY, and MALWARE_ANALYSIS. My thinking would be not to enable this field by default, you have to ask for it specifically. Thoughts?

**Comment by mgoffin** [comment]
I'm on the fence about having to request the type all the time. Can we think of any scenarios where we might want to include it by default? Connections come to mind if people can't/don't want to derive that from the connection type?

What URL parameter would we use to say that we want to include this field?

For pytx it would be useful to have it all the time so we can throw an exception if someone attempts to populate a class with the wrong object contents. We could technically always add the required URL parameter to every request but that would get a bit hackish when trying to protect the developer from doing the wrong thing :)

**Comment by jessek** [comment]
We can easily include the object_type field by default, but then it will always be included by default. In other words, when requesting to view 856783741064689, yes, it would be good to include the object_type field so that you know the object is a malware analysis, e.g.

    {
      "object_type": "MALWARE_ANALYSIS",
      "added_on": "2015-06-09T00:23:27+0000", 
      "md5": "9037a098b8b835cde8c3e2005fce6d3c", 
      "sha1": "6ff25da8a9de99956d385747c6318e28ab693519", 
      "sha256": "89b4d488fa02d85dcb19c43b6e6953fc4eb60fb27613609be56d6bb780243e1f", 
      "status": "UNKNOWN", 
    }

But because of how the Graph API works, a default field will always be included. In other words, if you search for /malware_analyses?since=yesterday, you'll get 25 blobs, each of which contain the (now redundant) object_type field. 

I don't know if that's a concern, but it's something I thought about.

You can always request specific fields using the 'fields' parameter, e.g

/856783741064689?fields=sha256,password
or
/malware_analyses?since=today&fields=sha256,password

[Note: That's a real ID, but I've changed the hashes]

**Comment by ivanlei** [comment]
Adding `object_type`, whether I have special request it or I always get it, would be nice.

**Comment by jessek** [comment]
I've been working on this and our team feels strongly that the Right Way(tm) to get the object's type is to specify 'metadata=1' in the request.

I'm sorry, but this is a won't fix.
