### ISSUE TITLE
When tmk-query-with-faiss which is more efficient than tmk-query can be support?

### ISSUE THREAD

**Issue by yfq512** [facebook/ThreatExchange#416]
tmk-query is slow when you have many tmk files , When tmk-query-with-faiss which is more efficient than tmk-query can be support ?

**Comment by Dcallies** [comment]
Hey @yfq512 , thanks for checking out ThreatExchange! We are looking into FAISS indexing support as a followup to https://github.com/facebook/ThreatExchange/issues/395. However, as planned this would be using the python wrapper. 

If you are interested in using FAISS, it should work more-or-less out of the box, and the only trick is to index the short (first 1kb) of TMK hash into FAISS, and then do linear matching on any matches afterwards.
