### ISSUE TITLE
Search does not recognize '@' symbol

### ISSUE THREAD

**Issue by jessek** [facebook/ThreatExchange#42]
The ThreatExchange search does not appear to recognize the '@' symbol in searches. Looking @evilevil, for example, would return some results which contain "evilevil", but not the '@' symbol.

**Comment by omercnet** [comment]
:+1: 

This is not limited just to @
searching yahoo does not return yahoo.com but only yahoo@otherdomain.com

**Comment by jessek** [comment]
I'm not sure what you mean in your last comment. Did you have other special characters in your search query? Are you specifying a type parameter? What kinds of data were you expecting to get back?

**Comment by omercnet** [comment]
when I query text=yahoo I wanna get 'yahoo' in any part of the string, all of the following are examples of expected results

yahoo@domain.com
user@yahoo.com
user@yahoo-inc.com
user@yahoo.br
user@notyahoo.com

**Comment by hammem** [comment]
It seems this is fixed now. For example, `/threat_indicators?text=@yahoo.com&strict_text=1` is now working.  @omercnet , can you confirm?

**Comment by jessek** [comment]
With no response from @omercnet  after three weeks, I am closing. Please re-open if you are still experiencing problems!

**Comment by omercnet** [comment]
sorry guys I missed Mike's response, it does seem to be fixed - thanks!
