### ISSUE TITLE
PDQ - Python and CPP hash outputs do not match..

### ISSUE THREAD

**Issue by shekarc** [facebook/ThreatExchange#447]
I tested the PDQ Implementation between CPP and Python and found there are some minor or some significant differences in the hashes they generate for the same images.  The details are attached here.
System configuration used for testing:  
Ubuntu 20.04 LTS (Focal fossa), 
CPP - Version: ImageMagick 7.0.11-3 Q8 x86_64 2021-03-06 https://imagemagick.org
Python - Python 3.8, with latest Pillow and Image Version

Attachments are: CPP-Data (CPP generated hashes), Python-Data (Python generated hashes) and the 10 Images Used.  _The image names got messed up when I dragged them to this, so, the names in the data file may not match._

[CPP2-Data.txt](https://github.com/facebook/ThreatExchange/files/6186007/CPP2-Data.txt)
[Python-Data.txt](https://github.com/facebook/ThreatExchange/files/6186008/Python-Data.txt)
![road](https://user-images.githubusercontent.com/2100212/112073609-b4ecac80-8b31-11eb-8e10-41504b6a2ed6.jpg)
![Trump2](https://user-images.githubusercontent.com/2100212/112073611-b5854300-8b31-11eb-9470-5d87b60b125b.jpg)
![Trump3](https://user-images.githubusercontent.com/2100212/112073612-b61dd980-8b31-11eb-97c9-4c8a5194274f.jpg)
![Trump4](https://user-images.githubusercontent.com/2100212/112073613-b61dd980-8b31-11eb-8f7e-d4470e29741f.jpg)
![Trump5](https://user-images.githubusercontent.com/2100212/112073614-b6b67000-8b31-11eb-9315-2f489daedaf6.jpg)
![Trump6](https://user-images.githubusercontent.com/2100212/112073615-b6b67000-8b31-11eb-9a49-1b77019f47f6.jpg)
![Trump7](https://user-images.githubusercontent.com/2100212/112073616-b6b67000-8b31-11eb-973a-93ea1d8d0b7a.jpg)
![Trump8](https://user-images.githubusercontent.com/2100212/112073617-b6b67000-8b31-11eb-99fe-7e4ee1674002.jpg)
![Trump9](https://user-images.githubusercontent.com/2100212/112073620-b74f0680-8b31-11eb-85d9-e198f50c2b7e.jpg)
![Trump10](https://user-images.githubusercontent.com/2100212/112073621-b74f0680-8b31-11eb-81ec-a626f6f331eb.jpg)

Please do not read anything into the choice of images, it was merely random and coincidental! :-)  (From [Google)](url)

P.S. I ran the CPP Code using an ImageMagic Version: ImageMagick 6.9.10-23 Q16 x86_64 20190101, and they yielded identical results.

**Comment by Usernamezhx** [comment]
I think you can check the image read and prepocess such as the way they read or resize. make sure the input before pdq is normal.

**Comment by Dcallies** [comment]
@BarrettOlson - we talked about this offline, and never circled back here - our theory was that it was also pre-processing, since py PDQ just calls into the cpp PDQ.

**Comment by BarrettOlson** [comment]
Yes, I looked at the hashes in the files provided and the distance between them is small enough that I'm not too concerned. Pre-processing is a likely explanation.

**Comment by Dcallies** [comment]
@BarrettOlson - Should we set expectations for different implementations in the README? Something like "Even if given the same image, there may be small distance changes due to [reasons], though they should not be greater than (some small observed value)"? Can we say that scaled to a certain size ahead of time that there will not be differences? (I can't recall the matrix size off the top of my head, but I think it's something like 128x128).

"If resized to (small value)" all versions should produce the same hash"

**Comment by BarrettOlson** [comment]
Even downscaled I'm not sure we can guarantee complete consistency. I'd need to improve my understanding of the PDQ algorithm further to make a strong claim in the README but I think a note about a certain margin of error and maybe the exact environment in which the unit test hashes were created would be valuable.

**Comment by codepujan** [comment]
Any updates / developments on this issue ? I seem to be facing the same problem.
