### ISSUE TITLE
pdq_hasher - Buffer has wrong number of dimensions (expected 3, got 2)

### ISSUE THREAD

**Issue by tgthorley** [facebook/ThreatExchange#455]
If images only have two dimensions (e.g. QR codes) pdqhash fails because it is expecting an array with 3 dimension

```
/opt/conda/lib/python3.8/site-packages/threatexchange/hashing/pdq_hasher.py in pdq_from_file(path)
     22     img_pil = Image.open(path)
     23     image = numpy.asarray(img_pil)
---> 24     return _pdq_from_numpy_array(image)
     25 
     26 

/opt/conda/lib/python3.8/site-packages/threatexchange/hashing/pdq_hasher.py in _pdq_from_numpy_array(array)
     34 
     35 def _pdq_from_numpy_array(array: numpy.ndarray) -> PDQOutput:
---> 36     hash_vector, quality = pdqhash.compute(array)
     37 
     38     bin_str = "".join([str(x) for x in hash_vector])

/opt/conda/lib/python3.8/site-packages/pdqhash/bindings.pyx in pdqhash.bindings.compute()

ValueError: Buffer has wrong number of dimensions (expected 3, got 2)
```

Example image is attached: 

![A Brief Introduction to Neural Networks (neuronalenetze-en-zeta2-2col-dkrieselcom) pdf_897](https://user-images.githubusercontent.com/3315649/112519685-fcad4700-8d70-11eb-8527-aa38bf18e86d.png)

**Comment by tgthorley** [comment]
Update - our of a corpus of 63950 images (extracted from pdfs) I found 544 images that caused this error all of them are black and white (though there is a variety of scanned text, QR codes and hand-drawn diagrams etc.)

**Comment by BarrettOlson** [comment]
Thanks so much for flagging this! Based on my reading of our c++ pdq code there is some nuance on how exactly to handle pdq for grayscale/black and white photos. I'm not convinced #465 is a complete fix but it should address the error and it does seem to generate the correct hashes based on my initial testing. 

I will follow up once it and a dependent PR are reviewed and merged. Thanks again!
