### ISSUE TITLE
[HMA] Upload pages do not work on firefox 

### ISSUE THREAD

**Issue by schatten** [facebook/ThreatExchange#598]
**Repro:**
1. Open the submit page on firefox eg. https://d3jelb9xcmkers.cloudfront.net/submit
2. Open the console using <cmd>+<shift>+<c> on mac
2. Select a file to submit

**Stacktrace:**
```
Uncaught TypeError: e.nativeEvent.path is undefined
    handleInputChangeUpload SubmitContent.jsx:55
    React 11
    unstable_runWithPriority scheduler.production.min.js:18
    React 3
SubmitContent.jsx:55:17
    handleInputChangeUpload SubmitContent.jsx:55
    React 11
    bind_applyFunctionN self-hosted:1371
    Xt self-hosted:1334
    unstable_runWithPriority scheduler.production.min.js:18
    React 3
    bind_applyFunctionN self-hosted:1371
    Jt self-hosted:1334
```

**Screenshot:**
<img width="1819" alt="Screen Shot 2021-05-19 at 13 13 55" src="https://user-images.githubusercontent.com/217056/118855749-259b1580-b8a4-11eb-9aee-55155a06bbb1.png">

**Comment by BarrettOlson** [comment]
https://stackoverflow.com/questions/39245488/event-path-is-undefined-running-in-firefox
