### ISSUE TITLE
HMA Wiki: Reference / PDQ Hashing

### ISSUE THREAD

**Issue by BarrettOlson** [facebook/ThreatExchange#609]
https://github.com/facebook/ThreatExchange/wiki/Reference-PDQ-Hashing

**Comment by Dcallies** [comment]
How did you choose how much to put in this article vs in the PDQ page? Why not just have everything be "See threatexchage/pdq"?

**Comment by Dcallies** [comment]
> PDQ currently the only matching signal type HMA supports. 

This can probably be omitted. 

Should we make a new section header for SignalType?

**Comment by Dcallies** [comment]
PDQ Hashes are created form 

form => from

**Comment by Dcallies** [comment]
> each content/images submitted to the system

This feels slightly clunky, might be possible to rephrase without a /

**Comment by schatten** [comment]
Link to 'Hamming Distance'?

PS: Github does not do subdirectories so I can empathize with your title. Just PDQ Hashing is also fine.

**Comment by schatten** [comment]
If the goal is to just have this much content, perhaps we could rename this page as "Supported Matching Algorithms" and have "PDQ for Photos" as a subheading?

Subjective Opinion: It looks too tiny to have its own page.

**Comment by Dcallies** [comment]
(Repeat of in-person comment): I think having the common attacks image helps a lot at visualizing what the algorithm does, and would suggest it at this point.

**Comment by Dcallies** [comment]
Depending on the audience, it may be enough to say "PDQ is an image similarity algorithm", link it to the github, and spend the rest of the document talking about what image similarity means.

**Comment by BarrettOlson** [comment]
Agree with all points, I think this instead should be focused on revamping the PDQ README.md I have updated the links on the wiki to go to https://github.com/facebook/ThreatExchange/tree/master/pdq#readme for now and am moving this issue back a column. Thanks!
