### ISSUE TITLE
Action Settings Page Design Feedback

### ISSUE THREAD

**Issue by schatten** [facebook/ThreatExchange#621]
* Save / Cancel sections on the edit modes. Add margin between Save and cancel buttons. 
* Use muted color, not red for cancel. Cancel in this case is not destructive.
<img width="435" alt="Screen Shot 2021-05-24 at 15 24 48" src="https://user-images.githubusercontent.com/217056/119405028-a300c480-bcae-11eb-98ae-faa1a3a5ade2.png">

Additionally, 
* Move the 'add' button to the right of the page header
* Move the 'edit rule' button to the right of the row

**Comment by BarrettOlson** [comment]
Larger refactor needed. Closing due to staleness.
