### ISSUE TITLE
HMA Wiki: Tutorials / How do I setup a webhook to be called when my content matches a dataset

### ISSUE THREAD

**Issue by jeberl** [facebook/ThreatExchange#633]
Review link: https://github.com/facebook/ThreatExchange/wiki/Tutorial:-How-to-Notify-My-System-when-My-Content-Matches-a-Dataset

**Comment by schatten** [comment]
| HMA allows you to configure when webhooks are sent, what url address they are sent to, and with what parameters. 

Was a little hard to read. Can we actually configure _when_ webhooks are sent? It can be read as 'time' or as preconditions. Rephrase?

**Comment by schatten** [comment]
>  If a match is found, we want to notify our system so that one of our reviewers can confirm that it is, in fact, a cat.

One of "your" reviewers.

**Comment by schatten** [comment]
super-nit: The tone varies. Some places we are using 'you' indicating second person, while some places we are using 'we' indicating first person. Can more consistent? Perhaps a standard tone throughout the documentation?

**Comment by schatten** [comment]
> First, we need to set up a client-side endpoint on our infrastructure to receive the webhooks...

I'm certain you mean 'server-side' endpoint.

**Comment by schatten** [comment]
Love the stepwise layout! 

In step-4: 
> depending on how many images you upload there may be a delay in the webhook being triggered of up to 15 minutes. 

I believe the max wait time will be lesser 4 minutes. AFAIK.

**Comment by jeberl** [comment]
Done and moved to done
