### ISSUE TITLE
HMA Wiki: Concepts / How does your media flow through the HMA?

### ISSUE THREAD

**Issue by schatten** [facebook/ThreatExchange#646]
[Link to review](https://github.com/facebook/ThreatExchange/wiki/How-does-your-media-flow-through-HMA%3F)

**Comment by Dcallies** [comment]
This page has the image I thought should be on #606

**Comment by Dcallies** [comment]
YMMV: Would suggest breaking the API calls to "API calls with Content" and "API calls with Signals" to make it clear that content stays inside cloud account

**Comment by Dcallies** [comment]
Nit: Inconsistent image element ordering: one arrow goes under the dotted line, one goes over it.

**Comment by Dcallies** [comment]
I think this needs a reference to the metadata/platform id concept as well.
