### ISSUE TITLE
HMA Wiki: Pages / Submit Content

### ISSUE THREAD

**Issue by BarrettOlson** [facebook/ThreatExchange#650]
https://github.com/facebook/ThreatExchange/wiki/Submit-Content

**Comment by Dcallies** [comment]
I can't really tell the difference between this page and https://github.com/facebook/ThreatExchange/wiki/Content-Submissions-API. If this is a UI, it seems like this information should be in tooltips.

If this UI is just a passthrough to the API, seems like it should just link to the API page.

**Comment by BarrettOlson** [comment]
@schatten meta question:
Are we looking for feedback on the content or the structure? I appreciate the reviews and feedback but this is the second time that I've received "why does this page exist compared to this one" style feedback which is more about the card itself. I I didn't establish the initial structure and don't want to mess with it without talking to the person who did...

**Comment by jeberl** [comment]
Made a few edits but looks good to me!

**Comment by schatten** [comment]
The "Pages" and the "API Reference" entries will be used at different phases. Submit Content via the UI will be done first. Yes, some of the information can be in tooltips. The wiki entry can be linked to for more verbose explanations.

IMO, It is okay for there to be duplicate content as long as they are to be read at different points in time.
