### ISSUE TITLE
HMA Wiki: Reference / Content Submissions API

### ISSUE THREAD

**Issue by BarrettOlson** [facebook/ThreatExchange#651]
https://github.com/facebook/ThreatExchange/wiki/Content-Submissions-API

**Comment by Dcallies** [comment]
Should the API examples include the type (str, int, etc)?

**Comment by jeberl** [comment]
Changes Requested:
- Can you describe what all of the submission type strings mean?
- Unclear what `file_type` means
- Dont understand this sentence:
>         - Best practice is submitting the same unique identifier used in the system submitting content to your deployed HMA.
