### ISSUE TITLE
HMA Wiki: Make external links open in a new tab

### ISSUE THREAD

**Issue by mengyangwang** [facebook/ThreatExchange#657]
I was checking solutions for this issue, but seems there is no simple way to do that. Github does not include the target attribute even if you use plain HTML. There are two options I can think of:
1. use an extra link https://github.com/namishkhanna/newtab, but it's not very user friendly
2. ask users to do a CTRL+click (on Windows and Linux) or CMD+click (on MacOS) on the link, it will open a new tab

**Comment by eriksendc** [comment]
If it's not possible, it's not possible! :)
