### ISSUE TITLE
Action Rules config page should show feedback if it could not save

### ISSUE THREAD

**Issue by schatten** [facebook/ThreatExchange#674]
<img width="1210" alt="Screen Shot 2021-06-15 at 14 30 04" src="https://user-images.githubusercontent.com/217056/122105626-0336e200-cde7-11eb-8de1-83b6ed286d95.png">

As shown above, at present, if you provide a malformed JSON value in either "Labeled As" or "Not Labeled As" fields, and click ✔️, it behaves as if it saved. A new row is inserted, but the values are not actually saved to the database.

The page should show server-side errors if they occur and update the UI.

**Comment by BarrettOlson** [comment]
Larger refactor needed, changes not being saved issue exists across pages. Closing due to staleness.
