### ISSUE TITLE
Long duration in pulling Malware Connections

### ISSUE THREAD

**Issue by cybercuffs** [facebook/ThreatExchange#68]
Reopening the issue reported in bug #46.

I did another experiment today and following are the stats of pulling dropped, dropped_by and malware, for only 3 minutes period. are below Each of the following data was pulled with since=1433167932 and until=1433168114. (i.e. 3 minutes duration). Note that malware took less than a minute, but dropped and dropped by took 5 and 6 minutes to pull 3 minutes of data. Is this expected or something we are aware of and working? Thanks!

$ ./malware.py 
Execution Started: 2015/08/28 20:26:43
Execution Completed: 2015/08/28 20:27:23

$  ./dropped_by.py 
Execution Started: 2015/08/28 20:29:32
Execution Completed: 2015/08/28 20:34:39

$ ./dropped.py 
Execution Started: 2015/08/28 20:38:52
Execution Completed: 2015/08/28 20:44:18

**Comment by jessek** [comment]
We have made several improvements to our searching infrastructure since you originally opened this issue. Are you still experiencing these long running times?
