### ISSUE TITLE
[HMA] S3 config hardcoded and setup instructions not provided

### ISSUE THREAD

**Issue by gifct-tech** [facebook/ThreatExchange#698]
When running spinning up an instance as per the ReadMe instructions the makefile calls a bunch of scripts. In scripts/write_backend_config.sh the s3 buckets names are hard coded  - while this works for ThreatExchange for other users looking to spin up an instance it will wrongly point to threat-exchanges s3 bucket.

Since this backend is optional there also are no setup instructions for the backend.tf

**Comment by BarrettOlson** [comment]
@gifct-tech Thanks for calling this out! 

Hopefully this is now addressed with the changes to the make command and the documentation. Feel free to reopen the issue if not.
