### ISSUE TITLE
Expose the descriptor creation time using the added_on field

### ISSUE THREAD

**Issue by jessek** [facebook/ThreatExchange#73]
Under v2.3, we had a field 'added_on', which was the creation time for an indicator. With descriptors in v2.4, we have no notion of when a descriptor was created. We should expose this creation time with the field 'added_on'.

**Comment by mgoffin** [comment]
+1

**Comment by alexcpsec** [comment]
yes, please :)

**Comment by RyPeck** [comment]
+1

**Comment by motiwarifacebook** [comment]
This is done: try threat_descriptors?since=1&fields=added_on.
