### ISSUE TITLE
[python-threatexchange] Index base class to support load() and save() methods

### ISSUE THREAD

**Issue by schatten** [facebook/ThreatExchange#733]
In some of the work we are doing in Video MD% support, load and save methods are being added to SignalTypeIndex subclasses in hmalib. This might be a problem down the line if python-threatexchange were to use filesystem backed indexes.

While the MRO would still allow hmalib's overrides to work, it seems clowny to override via a mixin without acknowledging.

So:
- add load() / save() /( store() ?) method signatures to SignalTypeIndex
- override rather than mixin that behavior in hmalib.

**Comment by Dcallies** [comment]
This implementation was rewritten, @schatten is this still valid?
