### ISSUE TITLE
pytx support for previous versions

### ISSUE THREAD

**Issue by RyPeck** [facebook/ThreatExchange#75]
When the 2.4 Graph API came out there were some significant changes to the ThreatExchange API. pytx accurately reflects those changes - but doesn't look to make an effort to enable use of the previous version.

I would like to use pytx to query the old `/threat_indicators` endpoint. But I don't see a parameter or method to override the API version used by `Common`.

[Recent changes](https://github.com/facebook/ThreatExchange/commit/e3e5d7f9c9673b6870fc974872d6e49f7861e7f0#diff-6d442426921d04ddf812c7f2e3a3ef2aL13) also blew away the fields that were associated with the ThreatIndicators class as well.

I understand the value of staying current. But for me to use the deprecated but still available v2.3 API Call `/threat_indicators` I would need to downgrade my pytx module.

Support could be maintained for previous version - or perhaps the line should be drawn that the module only supports the latest version.

**Comment by jessek** [comment]
Pardon my lack of GitHub experience, but can we make a separate branch for v2.3 support? I'd be happy to accept patches to such a branch. We'd have to cherry pick the changes which apply to things outside of the v2.3/2.4 split.

If you're willing to help get that off the ground, we can approve it at this end. 

My only concern that is that we'll be turning off all support for v2.3 in December 2015. That's only a few months away! :)

**Comment by mgoffin** [comment]
This was sort of a decision on my end. With 2.4 being so drastically different, and ( @jessek correct me if I'm wrong ) with previous versions being deprecated in a couple months, I decided to version-lock this release to 2.4. I use the term "version-lock" very loosely here as all I did was set ThreatExchange.VERSION to 'v2.4/' (https://github.com/facebook/ThreatExchange/blob/master/pytx/pytx/vocabulary.py#L8) and update the vocabulary and available fields appropriately.

If you wish to use previous versions while using the latest version of pytx, you can still use the Broker:

```python
url = ThreatExchange.URL + 'v2.3/' + ThreatExchange.THREAT_INDICATORS
response = Broker.get(url, params={'text': 'foo'})
```

It doesn't give you some of the nice stuff that the classes do, but if you absolutely need to query previous versions it's at least available. If you really need the older version objects, you can use a previous release of pytx for those. The previous versions supported all < 2.4 versions of the Graph API.

**Comment by jessek** [comment]
As it's now December and we are getting ready to turn off support for v2.3, I am going to close this out.
