### ISSUE TITLE
Unexpected keyword "status" when searching ThreatDescriptors

### ISSUE THREAD

**Issue by 9b** [facebook/ThreatExchange#83]
When searching for ThreatDescriptors using the "objects" interface in pytx, it does not seem to match the documentation displayed on the Facebook developers site - https://developers.facebook.com/docs/threat-exchange/reference/apis/threat-descriptors.

```
from pytx import init
from pytx import ThreatDescriptor
from pytx.vocabulary import Status

init(app_id='<app-id>', app_secret='<app-secret>')
results = ThreatDescriptor.objects(
    text='37.59.224.217',
    strict_text=True,
    status=Status.MALICIOUS
)
```

When running the code above, the following comes back:

```
Traceback (most recent call last):
  File "app/tools/threat_exchange.py", line 35, in <module>
    status=Status.MALICIOUS
TypeError: objects() got an unexpected keyword argument 'status'
```

**Comment by jessek** [comment]
Hmm. This query *should* work, e.g. 

  /threat_descriptors?text=37.59.224.217&strict_text=true&status=MALICIOUS

I'm not sure why pytx chokes on it.

**Comment by 9b** [comment]
Is it worth including labels for things like "library" or for the specific implementations? Something so that folks like @mgoffin know there's an issue?

**Comment by mgoffin** [comment]
`status` isn't an option to `.objects()` as of right now, which is a bug and should be fixed. Thanks for pointing it out!

**Comment by 9b** [comment]
Pull request submitted to add status and owner to the requests.

**Comment by mgoffin** [comment]
Thanks! Took a look and added some comments.
