### ISSUE TITLE
Control where "strict_text" is applied when searching

### ISSUE THREAD

**Issue by 9b** [facebook/ThreatExchange#84]
The current "strict_text" parameter is great for reducing fuzzy matches, but I've noticed that while it uses my exact query, it seems to apply across all fields. It would be helpful to specify the exact field I would like my "strict_text" query to run against. 

Example use case: 
```
from pytx import init
from pytx import ThreatDescriptor
from pytx.vocabulary import Types

init(app_id='<app-id>', app_secret='<app-secret>')
results = ThreatDescriptor.objects(
    text='haberko.com',
    strict_text=True,
    type_=Types.DOMAIN
)
```
When executing the above example, two different descriptors come back. One is an exact match (based on indicator) while the other was found just because the query was found in the comment. My use case is to get information about the exact indicator I queried for and nothing else, so having to loop over results to check where the match occurring is an extra step and potentially long one if the item being queried is more popular. Maybe allow for the user to specify the field to match against and just default to _all like it currently does now.

**Comment by jessek** [comment]
We haven't forgotten about this! I'm testing out a change now which would limit strict_text searches to the primary field (name, indicator, etc) for the type of data being searched.

**Comment by mgoffin** [comment]
That would be useful! If the change doesn't work, would it be breaking things too much to convert strict_text from a Boolean to a string which represents the field to apply strict searching on?

**Comment by jessek** [comment]
I'd like to keep strict_text as a boolean. We can change it's exact behavior, but what @mgoffin is proposing will be better in a different field. (text_field=description ?) A person may want to search another field with or without wildcards. (text="Jesse's best C2 server"&text_field=description&strict_text=1 vs. text="APT555"&field=description)

Regardless, the code to modify the behavior of strict_text has passed initial testing and is in the queue to be pushed next week. Using the example from above, I am now able to limit the data being returned s.t. that the text field must be in the indicator when strict_text is true.

I'm going to leave this open until the code is pushed and you can test it out. Let's revisit this next Wednesday and hopefully close this out.

**Comment by mgoffin** [comment]
@jessek I like your suggestion even better! :+1:

**Comment by jessek** [comment]
Is the new strict text working for you?

**Comment by jessek** [comment]
I'm going to close this issue out now, but please reopen it if you have any issues.
