### ISSUE TITLE
Copy/Paste code examples in API documentation

### ISSUE THREAD

**Issue by 9b** [facebook/ThreatExchange#85]
The value of a copy/paste example when looking at API documentation cannot be overstated. In the current API documents, endpoints and GET/POST content is shown, but it would be nice to have an example I could just copy/paste (think how Google does it) in the top 3-4 languages (Python, Java, PHP).

While it's not terribly difficult to convert the outlined requests into code, it's yet another set of steps that stop me from instantly plugging ThreatExchange into my project. Additionally, it could also be useful to include a hosted version of the JSON code, so I could load it directly from the FB developer site for testing or download it locally.

**Comment by mgoffin** [comment]
Would be worth enhancing the pytx `readthedocs` (https://pytx.readthedocs.org/en/latest/index.html) with the same exact code examples that get put into the developer docs.

**Comment by motiwarifacebook** [comment]
I'm closing this as I've published examples on the Getting Started and endpoint pages.

I haven't yet published examples using pytx, though I think that would be very valuable. I've test-driven pytx briefly and there were a lot of things I wanted to update on the documentation. Once I've written examples in pytx, I'll update the pytx readthedocs as well as the TX API reference with those examples.

**Comment by mgoffin** [comment]
I'd love to chat about the pytx stuff! Whether it's issues using it, ways to improve it, ways to make the examples better, or ways to better the documentation. Let me know!

**Comment by motiwarifacebook** [comment]
Definitely! I'm getting on a plane to India now on PTO, will let you know when I'm back!
