### ISSUE TITLE
incorrect license information and legal advice

### ISSUE THREAD

**Issue by Hello71** [facebook/ThreatExchange#868]
LICENSE and pdq/LICENSE.txt claim that the entire repository is under BSD license, which is not accurate.

pdq/cpp/README.md claims that "`CImg.h` ... license does not allow commercial use", which is not accurate.

**Comment by Dcallies** [comment]
Woah, thanks for the report!

**Comment by Dcallies** [comment]
Alright after some internal discussion, here's what we think we should do:

1. Delete the LICENSE files except the top level
2. Remove the mention on interpretation of the CImg.h license
3. Explicitly call out the exceptions to the entire repository statement in the readme. So for that it will say something like:

```
README
----------

# LIcense
The entire repository is under the BSD license, with a small number of exceptions listed in the file itself. With any luck, this is the complete list of exceptions:
1. pdq/cpp/CImg.h - Only included for demonstration purposes
```

@Hello71 - Do you think that will cover your concerns?

**Comment by Hello71** [comment]
that's not my preference, but at least it's accurate, if very minimal. LIcense is incorrectly capitalized though.

**Comment by Dcallies** [comment]
Unless there's anything else, will close us out!
