### ISSUE TITLE
API call to identify if "x was added to ThreatExchange" already

### ISSUE THREAD

**Issue by 9b** [facebook/ThreatExchange#88]
In order to identify if some indicator/descriptor has already been added to ThreatExchange for my app, I need to run a complicated query and then parse the results in an effort to surface the potential item. If I don't do this, I run into the potential of overwriting my existing input.

As an example use case, take the following:

I want to identify if I currently have a threat descriptor for evil.com. My query would need to include the following to potentially surface any existing TDs: owner as me, indicator as evil.com, potentially type and strict_text to avoid fuzzy matching. Even with a detailed query like that, it's entirely possible that I would get more than just my evil.com threat descriptor as evil.com could lie in the description of other descriptors I have sent in. So, I would need to parse the results, looking to ensure the "indicator" field was an exact match.

The way to combat this for now is to store FBIDs locally inside of some localized database, but assuming I have already sent data in, the above process is what I need to go through just to identify if I have already pushed data for a specific indicator. There's a lot of friction there.

**Comment by jessek** [comment]
Based on code we're pushing next week, this should hopefully be solved. Running a query based on owner, type, and text, with the newly improved strict_text parameter should fix this.

    /threat_descriptors?access_token=xxx|YYY&type=DOMAIN&owner=xxx&strict_text=true&text=evil.com

Should return only data submitted by you. You will still need to iterate through the returned values. A search for "evil.com" could return "subdomain.evil.com", for example.

This code is scheduled to push next Tuesday afternoon. I will leave this issue open until then, but let's circle back no later than 10 Dec to determine if we can close.

**Comment by mgoffin** [comment]
If this winds up being the solution, I can add a helper function in pytx which takes the text and auto-populates the rest of the parameters, queries for data, loops through the results, and returns (Boolean? Or maybe also include the ID?) whether or not your object exists already.

**Comment by jessek** [comment]
Does the provided solution work for you @9b?

**Comment by motiwarifacebook** [comment]
The strict_text and exact searching should resolve this problem
