### ISSUE TITLE
Updates to Threat Descriptors Fail

### ISSUE THREAD

**Issue by 9b** [facebook/ThreatExchange#89]
I am attempting to update the status of a threat descriptor and can't seem to get it to stick despite being returned a success. I have tried this through PyTX, and have used requests below as an example. Note, I am including the params as both data (POST) and params (GET) just in case, but have tried each independently with no luck.

```
import logging
import requests
from pytx.vocabulary import ThreatExchange as te

logging.basicConfig(level=logging.DEBUG)

auth = {
    'app_token': 'APP_TOKEN',
    'app_secret': 'APP_SECRET'
}
params = {'status': 'MALICIOUS'}
access_token = auth['app_token'] + '|' + auth['app_secret']
url = te.URL + str('907174782669741')
url = "%s?access_token=%s" % (url, access_token)
response = requests.post(
    url,
    params=params,
    data=params
)
print response.content
```

Here's the debugging output I am seeing:
```
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): graph.facebook.com
DEBUG:requests.packages.urllib3.connectionpool:"POST /907174782669741?access_token=<APP_TOKEN>%7C<APP_SECRET>&status=MALICIOUS HTTP/1.1" 200 16
Response: {"success":true}
```

**Comment by jessek** [comment]
I have identified the cause of this bug and will get a fix out immediately. Thank you for reporting it in such great detail!

**Comment by 9b** [comment]
Awesome! I am not crazy. :)

**Comment by jessek** [comment]
Well, nobody ever said *that*. ;-)

**Comment by jessek** [comment]
I am now able to update the status of descriptors via POST requests. Can you please test again from your end?

**Comment by 9b** [comment]
All good and clear to close.
