### ISSUE TITLE
Documentation for threat_descriptors submission should specify URL path correctly

### ISSUE THREAD

**Issue by johannestaas** [facebook/ThreatExchange#90]
https://developers.facebook.com/docs/threat-exchange/reference/submitting/v2.5

Where it says:
>You may submit data to the graph via an HTTP POST request the following URL:
>https://graph.facebook.com/threat_descriptors

Turns out nothing will work unless you specify the platform version you want to use:
https://graph.facebook.com/v2.4/threat_descriptors

Took me several hours figuring that one out, proxying the request, looking at the postdata... :( I finally found a URL in some code that had the platform version in the URL path and decided to try it out.

Anyway, RiskIQ is now submitting data to your platform!

johan.nestaas [[at]] riskiq.net

**Comment by motiwarifacebook** [comment]
Extremely sorry for the typo and the lost time. I've fixed this issue.

We're aware that are documentation needs some upkeep; we'll be doing a lot of repair on it over the next week.

**Comment by johannestaas** [comment]
No problem! Thanks for the fix.
