### ISSUE TITLE
ThreatExchange IOC

### ISSUE THREAD

**Issue by perez1987** [facebook/ThreatExchange#92]
Are ready to export the system alerts to IOC format?

**Comment by jessek** [comment]
I'm not sure what you're asking. All of the code we have for translating the ThreatExchange API format is hosted here on GitHub. Are you asking about the OpenIOC format, http://www.openioc.org/ ? We don't have any code for that right now, but would be happy to host it.

**Comment by jessek** [comment]
Did we address your concern? If so, can you please close out this issue. If not, what would you like to see?

**Comment by perez1987** [comment]
@jessek  OpenIOC I meant, but I see now does not support export alerts in that format. Thank you! You can close the ticket
