### ISSUE TITLE
Failed malware analysis example on documentation

### ISSUE THREAD

**Issue by 9b** [facebook/ThreatExchange#93]
Attempting to run the example in the documentation (https://developers.facebook.com/docs/threat-exchange/reference/apis/threat-indicator/v2.5) fails inside the graph explorer.

https://graph.facebook.com/v2.4/768629009848617/malware_analyses/?access_token=555|aSdF123GhK

**Comment by jessek** [comment]
Are you able to view 768629009848617 by itself?

**Comment by 9b** [comment]
I get the following when requesting it directly:

```
{
  "error": {
    "message": "Unsupported get request. Please read the Graph API documentation at https://developers.facebook.com/docs/graph-api",
    "type": "GraphMethodException",
    "code": 100,
    "fbtrace_id": "Bil+JpDLoV4"
  }
}
```

**Comment by hammem** [comment]
Thanks, @9b.  It should be fixed now.

**Comment by hammem** [comment]
Dah, I fixed a different issue in the docs :)  I'll fix this specific one as well.

**Comment by hammem** [comment]
Ok, for real this time.  It's fixed.
