### ISSUE TITLE
Add field to control which field is searched with the 'text' parameter

### ISSUE THREAD

**Issue by jessek** [facebook/ThreatExchange#96]
By default, we search all of the available fields using what's supplied in the 'text' parameter. Currently, the 'strict_text' parameter limits the search to the primary field (indicator or name). We should create a new field, 'text_field', which specifies which field should be searched using the 'text' parameter. For example,

```
/threat_descriptors?text="Jesse's best C2"&text_field=description&strict_text=1
```

should search the description field for exact matches to "Jesse's best C2".

See the discussion in https://github.com/facebook/ThreatExchange/issues/84 for background.

**Comment by Dcallies** [comment]
Hey all, we're doing a bulk cleanup of the current state of the repo. By default we're closing all the old issues unless we're sure what the next steps are. Feel free to comment or re-open if this is still affecting you or you think something should happen.

```
               ...
             ;::::;
           ;::::; :;
         ;:::::'   :;
        ;:::::;     ;.
       ,:::::'       ;           OOO\
       ::::::;       ;          OOOOO\
       ;:::::;       ;         OOOOOOOO
      ,;::::::;     ;'         / OOOOOOO
    ;:::::::::`. ,,,;.        /  / DOOOOOO
  .';:::::::::::::::::;,     /  /     DOOOO
 ,::::::;::::::;;;;::::;,   /  /        DOOO
;`::::::`'::::::;;;::::: ,#/  /          DOOO
:`:::::::`;::::::;;::: ;::#  /            DOOO
::`:::::::`;:::::::: ;::::# /              DOO
`:`:::::::`;:::::: ;::::::#/               DOO
 :::`:::::::`;; ;:::::::::##                OO
 ::::`:::::::`;::::::::;:::#                OO
 `:::::`::::::::::::;'`:;::#                O
  `:::::`::::::::;' /  / `:#
   ::::::`:::::;'  /  /   `#
```
