### ISSUE TITLE
ThreatExchange Privacy Controls Doc v2.5 says "feature that was removed after Graph API v2.3"

### ISSUE THREAD

**Issue by RyPeck** [facebook/ThreatExchange#97]
https://developers.facebook.com/docs/threat-exchange/reference/privacy/v2.5

When I visit I see `(!) This document refers to a feature that was removed after Graph API v2.3.`

I assume that is incorrect?

**Comment by motiwarifacebook** [comment]
Fixed, thanks for catching that!
