### ISSUE TITLE
[pytx][cli] threatexchange cli broken for python<3.8 

### ISSUE THREAD

**Issue by BarrettOlson** [facebook/ThreatExchange#975]
`force=True` in https://github.com/facebook/ThreatExchange/blob/main/python-threatexchange/threatexchange/cli/main.py#L200 causes errors for python < 3.8

if we want to support 3.6 and 3.7 we need to address this as part of fixing up `python-threatexchange` from #944

Source:
https://docs.python.org/3.9/library/logging.html#logging.basicConfig 
> Changed in version 3.8: The force argument was added.

**Comment by Dcallies** [comment]
I'd like to propose we deprecate access for <3.8 and unlock the walrus (and others)! Will bring it up in next team meeting.

**Comment by Dcallies** [comment]
We have now deprecated for <3.8
